/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FInputDataGuru.java
 *
 * Created on 26 Jun 13, 17:18:38
 */

package akademik_smppgri2bdg;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dey
 */
public class FInputDataGuru extends javax.swing.JFrame {
    public DefaultTableModel tabModel;
    Connection conn;

    /** Creates new form FInputDataGuru */
    public FInputDataGuru() {
        initComponents();
        setJTable();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        PanelDataGuru = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtTempatLahirGuru = new javax.swing.JTextField();
        dateLahirGuru = new com.toedter.calendar.JDateChooser();
        CBJKGuru = new javax.swing.JComboBox();
        CBAgamaGuru = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        CBStatusGuru = new javax.swing.JComboBox();
        CBGolonganGuru = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        txtNIP = new javax.swing.JTextField();
        txtNamaGuru = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtNoTelpGuru = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtAlamatGuru = new javax.swing.JTextField();
        CBKewarganegaraanGuru = new javax.swing.JComboBox();
        PanelTabelGuru = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TGuru = new javax.swing.JTable();
        PanelPencarianGuru = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        CBCariGuru = new javax.swing.JComboBox();
        txtCariGuru = new javax.swing.JTextField();
        BCariGuru = new javax.swing.JButton();
        PanelButtonGuru = new javax.swing.JPanel();
        BTambah = new javax.swing.JButton();
        BEdit = new javax.swing.JButton();
        BSimpan = new javax.swing.JButton();
        BHapus = new javax.swing.JButton();
        BBatal = new javax.swing.JButton();
        BKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Input Data Guru");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("INPUT DATA GURU");

        PanelDataGuru.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "DATA GURU :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel4.setText("NIP");

        jLabel5.setText("Nama Guru");

        jLabel17.setText("Tempat dan Tanggal Lahir");

        txtTempatLahirGuru.setEnabled(false);
        txtTempatLahirGuru.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTempatLahirGuruKeyTyped(evt);
            }
        });

        dateLahirGuru.setDateFormatString("yyyy-MM-dd");
        dateLahirGuru.setEnabled(false);

        CBJKGuru.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Pilih--", "Laki-Laki", "Perempuan" }));
        CBJKGuru.setEnabled(false);

        CBAgamaGuru.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Pilih--", "Islam", "Kristen", "Hindu", "Budha", "Lainnya" }));
        CBAgamaGuru.setEnabled(false);

        jLabel18.setText("Kewarganegaraan");

        jLabel19.setText("Agama");

        jLabel20.setText("Jenis Kelamin");

        jLabel21.setText("Status");

        CBStatusGuru.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Pilih--", "PNS", "PNS DEPAG", "NON PNS" }));
        CBStatusGuru.setEnabled(false);
        CBStatusGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBStatusGuruActionPerformed(evt);
            }
        });

        CBGolonganGuru.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Pilih--", "III A", "III D", "IV A", "IV B", "IV C" }));
        CBGolonganGuru.setEnabled(false);
        CBGolonganGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBGolonganGuruActionPerformed(evt);
            }
        });

        jLabel22.setText("Golongan");

        txtNIP.setEnabled(false);
        txtNIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNIPActionPerformed(evt);
            }
        });

        txtNamaGuru.setEnabled(false);
        txtNamaGuru.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNamaGuruKeyTyped(evt);
            }
        });

        jLabel23.setText("Nomor Telepon");

        txtNoTelpGuru.setEnabled(false);
        txtNoTelpGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoTelpGuruActionPerformed(evt);
            }
        });
        txtNoTelpGuru.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNoTelpGuruKeyTyped(evt);
            }
        });

        jLabel26.setText("Alamat");

        txtAlamatGuru.setEnabled(false);

        CBKewarganegaraanGuru.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Pilih--", "WNI", "WNA" }));
        CBKewarganegaraanGuru.setEnabled(false);

        javax.swing.GroupLayout PanelDataGuruLayout = new javax.swing.GroupLayout(PanelDataGuru);
        PanelDataGuru.setLayout(PanelDataGuruLayout);
        PanelDataGuruLayout.setHorizontalGroup(
            PanelDataGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDataGuruLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDataGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel22)
                    .addComponent(jLabel21)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel5)
                    .addComponent(jLabel26)
                    .addComponent(jLabel23))
                .addGap(10, 10, 10)
                .addGroup(PanelDataGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAlamatGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNIP, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBJKGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelDataGuruLayout.createSequentialGroup()
                        .addComponent(txtTempatLahirGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(dateLahirGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelDataGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(CBGolonganGuru, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CBStatusGuru, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CBKewarganegaraanGuru, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CBAgamaGuru, javax.swing.GroupLayout.Alignment.LEADING, 0, 94, Short.MAX_VALUE))
                    .addComponent(txtNoTelpGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        PanelDataGuruLayout.setVerticalGroup(
            PanelDataGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDataGuruLayout.createSequentialGroup()
                .addGroup(PanelDataGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDataGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDataGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDataGuruLayout.createSequentialGroup()
                        .addGroup(PanelDataGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTempatLahirGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelDataGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CBJKGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelDataGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(CBAgamaGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(dateLahirGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDataGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(CBKewarganegaraanGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDataGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBStatusGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDataGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBGolonganGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDataGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtAlamatGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDataGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNoTelpGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelTabelGuru.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "DATA TABEL GURU", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        TGuru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TGuru);

        javax.swing.GroupLayout PanelTabelGuruLayout = new javax.swing.GroupLayout(PanelTabelGuru);
        PanelTabelGuru.setLayout(PanelTabelGuruLayout);
        PanelTabelGuruLayout.setHorizontalGroup(
            PanelTabelGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTabelGuruLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelTabelGuruLayout.setVerticalGroup(
            PanelTabelGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTabelGuruLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelPencarianGuru.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel28.setText("Cari Berdasarkan");

        CBCariGuru.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NIP", "Nama Guru" }));
        CBCariGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBCariGuruActionPerformed(evt);
            }
        });

        BCariGuru.setText("Cari");
        BCariGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCariGuruActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPencarianGuruLayout = new javax.swing.GroupLayout(PanelPencarianGuru);
        PanelPencarianGuru.setLayout(PanelPencarianGuruLayout);
        PanelPencarianGuruLayout.setHorizontalGroup(
            PanelPencarianGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPencarianGuruLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addGap(6, 6, 6)
                .addComponent(CBCariGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCariGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BCariGuru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        PanelPencarianGuruLayout.setVerticalGroup(
            PanelPencarianGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPencarianGuruLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelPencarianGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(CBCariGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCariGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BCariGuru))
                .addContainerGap())
        );

        PanelButtonGuru.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelButtonGuru.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTambah.setText("Tambah");
        BTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTambahActionPerformed(evt);
            }
        });
        PanelButtonGuru.add(BTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, -1));

        BEdit.setText("Edit");
        BEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEditActionPerformed(evt);
            }
        });
        PanelButtonGuru.add(BEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 80, -1));

        BSimpan.setText("Simpan");
        BSimpan.setEnabled(false);
        BSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSimpanActionPerformed(evt);
            }
        });
        PanelButtonGuru.add(BSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 80, -1));

        BHapus.setText("Hapus");
        BHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHapusActionPerformed(evt);
            }
        });
        PanelButtonGuru.add(BHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 80, -1));

        BBatal.setText("Batal");
        BBatal.setEnabled(false);
        BBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBatalActionPerformed(evt);
            }
        });
        PanelButtonGuru.add(BBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 80, -1));

        BKeluar.setText("Keluar");
        BKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BKeluarActionPerformed(evt);
            }
        });
        PanelButtonGuru.add(BKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(PanelDataGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelButtonGuru, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                    .addComponent(PanelTabelGuru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelPencarianGuru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(414, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(285, 285, 285))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelDataGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(PanelPencarianGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelButtonGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PanelTabelGuru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTempatLahirGuruKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTempatLahirGuruKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (((c >= '0') && (c <= '9') && txtTempatLahirGuru.getText().length() < 25
                || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
}//GEN-LAST:event_txtTempatLahirGuruKeyTyped

    private void txtNamaGuruKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaGuruKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (((c >= '0') && (c <= '9') && txtNamaGuru.getText().length() < 50
                || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
}//GEN-LAST:event_txtNamaGuruKeyTyped

    private void txtNoTelpGuruKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoTelpGuruKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') && txtNoTelpGuru.getText().length() < 15
                || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
}//GEN-LAST:event_txtNoTelpGuruKeyTyped

    private void BCariGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCariGuruActionPerformed
        // TODO add your handling code here:
        String sql;
        int pilih = CBCariGuru.getSelectedIndex();
        String cari = txtCariGuru.getText();
        try {
            conn.close();
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            conn=DriverManager.getConnection("jdbc:odbc:akademik_smppgri2bdg");
            if(pilih==0)
                sql ="Select * from guru WHERE nip ='" +txtCariGuru.getText() + "'";
            else
                sql ="Select * from guru WHERE nama_guru Like '%" +txtCariGuru.getText() + "%'";

            PreparedStatement st = conn.prepareStatement(sql);
            ResultSet rs =st.executeQuery();

            hapusIsiJTable();
            int no=0;
            while (rs.next()) {
                no++;
                String nip = rs.getString("nip");
                String nama_guru = rs.getString("nama_guru");
                String tempat_lahir_guru = rs.getString("tempat_lahir_guru");
                String tanggal_lahir_guru = rs.getString("tanggal_lahir_guru");
                String jk_guru = rs.getString("jk_guru");
                String agama_guru = rs.getString("agama_guru");
                String kewarganegaraan_guru = rs.getString("kewarganegaraan_guru");
                String status_guru = rs.getString("status_guru");
                String golongan_guru = rs.getString("golongan_guru");
                String no_telp_guru = rs.getString("no_telp_guru");
                String alamat_guru = rs.getString("alamat_guru");

                Object [] data = {no,nip,nama_guru,tempat_lahir_guru,tanggal_lahir_guru,
                jk_guru,agama_guru,kewarganegaraan_guru,status_guru,golongan_guru,
                no_telp_guru,alamat_guru};
                tabModel.addRow(data);
            }

            if(tabModel.getRowCount()>0)
                JOptionPane.showMessageDialog(this,"Data Ditemukan ");
            else
                JOptionPane.showMessageDialog(this,"Data Tidak Ditemukan.. ");

        } catch (ClassNotFoundException se) {}
        catch (SQLException se) {}
    }//GEN-LAST:event_BCariGuruActionPerformed

    private void BTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTambahActionPerformed
        // TODO add your handling code here:
        txtNIP.setEnabled(true);
        txtNamaGuru.setEnabled(true);
        txtTempatLahirGuru.setEnabled(true);
        dateLahirGuru.setEnabled(true);
        CBJKGuru.setEnabled(true);
        CBAgamaGuru.setEnabled(true);
        CBKewarganegaraanGuru.setEnabled(true);
        CBStatusGuru.setEnabled(true);
        CBGolonganGuru.setEnabled(true);
        txtNoTelpGuru.setEnabled(true);
        txtAlamatGuru.setEnabled(true);

        BSimpan.setText("Simpan");

        BTambah.setEnabled(false);
        BSimpan.setEnabled(true);
        BEdit.setEnabled(false);
        BBatal.setEnabled(true);
        BHapus.setEnabled(false);
        BKeluar.setEnabled(false);
}//GEN-LAST:event_BTambahActionPerformed

    private void BEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEditActionPerformed
        // TODO add your handling code here:
        txtNIP.setEnabled(false);
        txtNamaGuru.setEnabled(true);
        txtTempatLahirGuru.setEnabled(true);
        dateLahirGuru.setEnabled(true);
        CBJKGuru.setEnabled(true);
        CBAgamaGuru.setEnabled(true);
        CBKewarganegaraanGuru.setEnabled(true);
        CBStatusGuru.setEnabled(true);
        CBGolonganGuru.setEnabled(true);
        txtNoTelpGuru.setEnabled(true);
        txtAlamatGuru.setEnabled(true);

        BSimpan.setText("Update");

        BTambah.setEnabled(false);
        BSimpan.setEnabled(true);
        BEdit.setEnabled(false);
        BBatal.setEnabled(true);
        BHapus.setEnabled(false);
        BKeluar.setEnabled(false);


        ambilData_dari_JTable();
}//GEN-LAST:event_BEditActionPerformed

    private void BSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSimpanActionPerformed
        // TODO add your handling code here:
        if(txtNIP.getText().isEmpty() ||
           txtNamaGuru.getText().isEmpty() ||
           txtTempatLahirGuru.getText().isEmpty() ||
           dateLahirGuru.getDateFormatString().isEmpty() ||
           CBJKGuru.getSelectedItem().equals("--Pilih--") ||
           CBAgamaGuru.getSelectedItem().equals("--Pilih--") ||
           CBKewarganegaraanGuru.getSelectedItem().equals("--Pilih--") ||
           CBStatusGuru.getSelectedItem().equals("--Pilih--") ||
           CBGolonganGuru.getSelectedItem().equals("--Pilih--") ||
           txtNoTelpGuru.getText().isEmpty() ||
           txtAlamatGuru.getText().isEmpty())
           {
            JOptionPane.showMessageDialog(this,"Data Tidak Lengkap!!");

           } else
             if(BSimpan.getText().equalsIgnoreCase("Simpan"))
                simpanData();
             else
                rubahData();

        txtNIP.setText("");
        txtNamaGuru.setText("");
        txtTempatLahirGuru.setText("");
        dateLahirGuru.setDateFormatString("");
        CBJKGuru.setSelectedItem("--Pilih--");
        CBAgamaGuru.setSelectedItem("--Pilih--");
        CBKewarganegaraanGuru.setSelectedItem("--Pilih--");
        CBStatusGuru.setSelectedItem("--Pilih--");
        CBGolonganGuru.setSelectedItem("--Pilih--");
        txtNoTelpGuru.setText("");
        txtAlamatGuru.setText("");

        txtNIP.setEnabled(false);
        txtNamaGuru.setEnabled(true);
        txtTempatLahirGuru.setEnabled(true);
        dateLahirGuru.setEnabled(true);
        CBJKGuru.setEnabled(true);
        CBAgamaGuru.setEnabled(true);
        CBKewarganegaraanGuru.setEnabled(true);
        CBStatusGuru.setEnabled(true);
        CBGolonganGuru.setEnabled(true);
        txtNoTelpGuru.setEnabled(true);
        txtAlamatGuru.setEnabled(true);

        txtNIP.setEnabled(false);
        txtNamaGuru.setEnabled(false);
        txtTempatLahirGuru.setEnabled(false);
        dateLahirGuru.setEnabled(false);
        CBJKGuru.setEnabled(false);
        CBAgamaGuru.setEnabled(false);
        CBKewarganegaraanGuru.setEnabled(false);
        CBStatusGuru.setEnabled(false);
        CBGolonganGuru.setEnabled(false);
        txtNoTelpGuru.setEnabled(false);
        txtAlamatGuru.setEnabled(false);

        BTambah.setEnabled(true);
        BSimpan.setEnabled(false);
        BEdit.setEnabled(true);
        BBatal.setEnabled(false);
        BHapus.setEnabled(true);
        BKeluar.setEnabled(true);
    }//GEN-LAST:event_BSimpanActionPerformed

    private void BHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHapusActionPerformed
        // TODO add your handling code here:
        hapus_Data();
}//GEN-LAST:event_BHapusActionPerformed

    private void BBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBatalActionPerformed
        // TODO add your handling code here:
        txtNIP.setText("");
        txtNamaGuru.setText("");
        txtTempatLahirGuru.setText("");
        dateLahirGuru.setDateFormatString("");
        CBJKGuru.setSelectedItem("--Pilih--");
        CBAgamaGuru.setSelectedItem("--Pilih--");
        CBKewarganegaraanGuru.setSelectedItem("--Pilih--");
        CBStatusGuru.setSelectedItem("--Pilih--");
        CBGolonganGuru.setSelectedItem("--Pilih--");
        txtNoTelpGuru.setText("");
        txtAlamatGuru.setText("");

        txtNIP.setEnabled(false);
        txtNamaGuru.setEnabled(false);
        txtTempatLahirGuru.setEnabled(false);
        dateLahirGuru.setEnabled(false);
        CBJKGuru.setEnabled(false);
        CBAgamaGuru.setEnabled(false);
        CBKewarganegaraanGuru.setEnabled(false);
        CBStatusGuru.setEnabled(false);
        CBGolonganGuru.setEnabled(false);
        txtNoTelpGuru.setEnabled(false);
        txtAlamatGuru.setEnabled(false);

        BTambah.setEnabled(true);
        BSimpan.setEnabled(false);
        BEdit.setEnabled(true);
        BBatal.setEnabled(false);
        BHapus.setEnabled(true);
        BKeluar.setEnabled(true);
}//GEN-LAST:event_BBatalActionPerformed

    private void BKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BKeluarActionPerformed
        // TODO add your handling code here:
        dispose();
}//GEN-LAST:event_BKeluarActionPerformed

    private void CBStatusGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBStatusGuruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBStatusGuruActionPerformed

    private void CBGolonganGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBGolonganGuruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBGolonganGuruActionPerformed

    private void txtNoTelpGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoTelpGuruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoTelpGuruActionPerformed

    private void txtNIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNIPActionPerformed

    private void CBCariGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBCariGuruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBCariGuruActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FInputDataGuru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBatal;
    private javax.swing.JButton BCariGuru;
    private javax.swing.JButton BEdit;
    private javax.swing.JButton BHapus;
    private javax.swing.JButton BKeluar;
    private javax.swing.JButton BSimpan;
    private javax.swing.JButton BTambah;
    private javax.swing.JComboBox CBAgamaGuru;
    private javax.swing.JComboBox CBCariGuru;
    private javax.swing.JComboBox CBGolonganGuru;
    private javax.swing.JComboBox CBJKGuru;
    private javax.swing.JComboBox CBKewarganegaraanGuru;
    private javax.swing.JComboBox CBStatusGuru;
    private javax.swing.JPanel PanelButtonGuru;
    private javax.swing.JPanel PanelDataGuru;
    private javax.swing.JPanel PanelPencarianGuru;
    private javax.swing.JPanel PanelTabelGuru;
    private javax.swing.JTable TGuru;
    private com.toedter.calendar.JDateChooser dateLahirGuru;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAlamatGuru;
    private javax.swing.JTextField txtCariGuru;
    private javax.swing.JTextField txtNIP;
    private javax.swing.JTextField txtNamaGuru;
    private javax.swing.JTextField txtNoTelpGuru;
    private javax.swing.JTextField txtTempatLahirGuru;
    // End of variables declaration//GEN-END:variables

    private void getData(){

  try{
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");

        conn=DriverManager.getConnection("jdbc:odbc:akademik_smppgri2bdg");

        String sql="Select * from guru";
        PreparedStatement st=conn.prepareStatement(sql);

        ResultSet rs=st.executeQuery();

        String nip,nama_guru,tempat_lahir_guru,tanggal_lahir_guru,
               jk_guru,agama_guru,kewarganegaraan_guru,status_guru,golongan_guru,
               no_telp_guru,alamat_guru;
        int no=0;
        while(rs.next()){
         no=no+1;
         nip=rs.getString("nip");
         nama_guru=rs.getString("nama_guru");
         tempat_lahir_guru=rs.getString("tempat_lahir_guru");
         tanggal_lahir_guru=rs.getString("tanggal_lahir_guru");
         jk_guru=rs.getString("jk_guru");
         agama_guru=rs.getString("agama_guru");
         kewarganegaraan_guru=rs.getString("kewarganegaraan_guru");
         status_guru=rs.getString("status_guru");
         golongan_guru=rs.getString("golongan_guru");
         no_telp_guru=rs.getString("no_telp_guru");
         alamat_guru=rs.getString("alamat_guru");
         Object [] Data = {no,nip,nama_guru,tempat_lahir_guru,tanggal_lahir_guru,
               jk_guru,agama_guru,kewarganegaraan_guru,status_guru,golongan_guru,
               no_telp_guru,alamat_guru};
         tabModel.addRow(Data);
        }

          st.close();
          conn.close();
    }
    catch (ClassNotFoundException cnfe) {
           System.out.println("Class Driver tidak ditemukan.. : " + cnfe);
           System.exit(0);
    }
    catch (SQLException sqle) {
           System.out.println("Proses Query Gagal = " + sqle);
           System.exit(0);
    }
    catch(Exception e){
           System.out.println("Koneksi Access Gagal " +e.getMessage());
           System.exit(0);
    }

    }

private void setJTable(){
    String [] JudulKolom={"No","NIP","Nama Guru","Tempat Lahir","Tanggal Lahir",
                          "Jenis Kelamin","Agama","Kewarganegaraan","Status","Golongan",
                          "No Telp","Alamat"};
    tabModel = new DefaultTableModel(null, JudulKolom){
                  boolean[] canEdit = new boolean [] { false, false, false, false, false,
                                                       false, false, false, false, false,
                                                       false, false };
                  @Override
                  public boolean isCellEditable(int rowIndex, int columnIndex) {
                   return canEdit [columnIndex];
                  }
              };
    TGuru.setModel(tabModel);
    TGuru.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
    TGuru.getColumnModel().getColumn(0).setPreferredWidth(30);
    TGuru.getColumnModel().getColumn(1).setPreferredWidth(100);
    TGuru.getColumnModel().getColumn(2).setPreferredWidth(100);
    TGuru.getColumnModel().getColumn(3).setPreferredWidth(100);
    TGuru.getColumnModel().getColumn(4).setPreferredWidth(100);
    TGuru.getColumnModel().getColumn(5).setPreferredWidth(100);
    TGuru.getColumnModel().getColumn(6).setPreferredWidth(100);
    TGuru.getColumnModel().getColumn(7).setPreferredWidth(100);
    TGuru.getColumnModel().getColumn(8).setPreferredWidth(100);
    TGuru.getColumnModel().getColumn(9).setPreferredWidth(100);
    TGuru.getColumnModel().getColumn(10).setPreferredWidth(100);
    TGuru.getColumnModel().getColumn(11).setPreferredWidth(100);

    getData();
}

void ambilData_dari_JTable() {
    int row = TGuru.getSelectedRow();

    String nip = tabModel.getValueAt(row, 1).toString();
    String nama_guru = tabModel.getValueAt(row, 2).toString();
    String tempat_lahir_guru = tabModel.getValueAt(row, 3).toString();
    String tanggal_lahir_guru = tabModel.getValueAt(row, 4).toString();
    String jk_guru = tabModel.getValueAt(row, 5).toString();
    String agama_guru = tabModel.getValueAt(row, 6).toString();
    String kewarganegaraan_guru = tabModel.getValueAt(row, 7).toString();
    String status_guru = tabModel.getValueAt(row, 8).toString();
    String golongan_guru = tabModel.getValueAt(row, 9).toString();
    String no_telp_guru = tabModel.getValueAt(row, 10).toString();
    String alamat_guru = tabModel.getValueAt(row, 11).toString();

    txtNIP.setText(nip);
    txtNamaGuru.setText(nama_guru);
    txtTempatLahirGuru.setText(tempat_lahir_guru);
    dateLahirGuru.setDateFormatString(tanggal_lahir_guru);
    CBJKGuru.setSelectedItem(jk_guru);
    CBAgamaGuru.setSelectedItem(agama_guru);
    CBKewarganegaraanGuru.setSelectedItem(kewarganegaraan_guru);
    CBStatusGuru.setSelectedItem(status_guru);
    CBGolonganGuru.setSelectedItem(golongan_guru);
    txtNoTelpGuru.setText(no_telp_guru);
    txtAlamatGuru.setText(alamat_guru);

    }

public void hapusIsiJTable() {
    int row = tabModel.getRowCount();
    for (int i = 0; i < row; i++) {
      tabModel.removeRow(0);
    }
  }

public void tampilDataKeJTable() {
    hapusIsiJTable();
    try {
        conn.close();
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        conn=DriverManager.getConnection("jdbc:odbc:akademik_smppgri2bdg");
        String sql="Select * from guru";
        PreparedStatement st=conn.prepareStatement(sql);
        ResultSet rs=st.executeQuery();
        String nip,nama_guru,tempat_lahir_guru,tanggal_lahir_guru,
               jk_guru,agama_guru,kewarganegaraan_guru,status_guru,golongan_guru,
               no_telp_guru,alamat_guru;
        int no=0;
        while(rs.next()){
         no=no+1;
         nip=rs.getString("nip");
         nama_guru=rs.getString("nama_guru");
         tempat_lahir_guru=rs.getString("tempat_lahir_guru");
         tanggal_lahir_guru=rs.getString("tanggal_lahir_guru");
         jk_guru=rs.getString("jk_guru");
         agama_guru=rs.getString("agama_guru");
         kewarganegaraan_guru=rs.getString("kewarganegaraan_guru");
         status_guru=rs.getString("status_guru");
         golongan_guru=rs.getString("golongan_guru");
         no_telp_guru=rs.getString("no_telp_guru");
         alamat_guru=rs.getString("alamat_guru");

         Object Data[]={no,nip,nama_guru,tempat_lahir_guru,tanggal_lahir_guru,
                        jk_guru,agama_guru,kewarganegaraan_guru,status_guru,golongan_guru,
                        no_telp_guru,alamat_guru};
         tabModel.addRow(Data);
      }
  }
    catch (Exception e) {}
}

public void rubahData() {

    int ok = JOptionPane.showConfirmDialog(this,
        "Anda Yakin Ingin Mengubah Data\n Dengan NIP = '" + txtNIP.getText() +
        "'", "Konfirmasi ",JOptionPane.YES_NO_OPTION);

    if (ok == 0) {
      try {
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        conn=DriverManager.getConnection("jdbc:odbc:akademik_smppgri2bdg");
        String sql ="UPDATE guru SET nama_guru = ?,tempat_lahir_guru = ?,tanggal_lahir_guru = ?,jk_guru = ?,agama_guru = ?,kewarganegaraan_guru = ?,status_guru = ?,golongan_guru = ?,no_telp_guru = ?,alamat_guru = ? WHERE nip = ?";
        PreparedStatement st = conn.prepareStatement(sql);
        try {
          st.setString(1, txtNamaGuru.getText());
          st.setString(2, txtTempatLahirGuru.getText());
          st.setString(3, String.valueOf(dateLahirGuru.getDate()));
          st.setString(4, String.valueOf(CBJKGuru.getSelectedItem()));
          st.setString(5, String.valueOf(CBAgamaGuru.getSelectedItem()));
          st.setString(6, String.valueOf(CBKewarganegaraanGuru.getSelectedItem()));
          st.setString(7, String.valueOf(CBStatusGuru.getSelectedItem()));
          st.setString(8, String.valueOf(CBGolonganGuru.getSelectedItem()));
          st.setString(9, txtNoTelpGuru.getText());
          st.setString(10, txtAlamatGuru.getText());
          st.setString(11, txtNIP.getText());
          st.executeUpdate();

        tampilDataKeJTable();

        txtNIP.setText("");
        txtNamaGuru.setText("");
        txtTempatLahirGuru.setText("");
        dateLahirGuru.setDateFormatString("");
        CBJKGuru.setSelectedItem("");
        CBAgamaGuru.setSelectedItem("");
        CBKewarganegaraanGuru.setSelectedItem("");
        CBStatusGuru.setSelectedItem("");
        CBGolonganGuru.setSelectedItem("");
        txtNoTelpGuru.setText("");
        txtAlamatGuru.setText("");
        } catch (SQLException se) { }
      } catch (ClassNotFoundException se) {}
      catch (SQLException se) {}
    }

  }

public void simpanData(){
    String tgllahir = "dd-MM-yyyy";
    SimpleDateFormat format = new SimpleDateFormat(tgllahir);
     try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            conn=DriverManager.getConnection("jdbc:odbc:akademik_smppgri2bdg");
            String sql="Insert into guru values(?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement st=conn.prepareStatement(sql);
                st.setString(1, txtNIP.getText());
                st.setString(2, txtNamaGuru.getText());
                st.setString(3, txtTempatLahirGuru.getText());
                st.setString(4, String.valueOf(format.format(dateLahirGuru.getDate())));
                st.setString(5, String.valueOf(CBJKGuru.getSelectedItem()));
                st.setString(6, String.valueOf(CBAgamaGuru.getSelectedItem()));
                st.setString(7, String.valueOf(CBKewarganegaraanGuru.getSelectedItem()));
                st.setString(8, String.valueOf(CBStatusGuru.getSelectedItem()));
                st.setString(9, String.valueOf(CBGolonganGuru.getSelectedItem()));
                st.setString(10, txtNoTelpGuru.getText());
                st.setString(11, txtAlamatGuru.getText());
            int rs=st.executeUpdate();

            if(rs>0){
            JOptionPane.showMessageDialog(this,"Input Berhasil");
      	    tampilDataKeJTable();
            }
            st.close();
            conn.close();
        }
        catch (ClassNotFoundException cnfe) {
           System.out.println("Class Driver tidak ditemukan.. : " + cnfe);
        }
        catch (SQLException sqle) {
           System.out.println("Input  Gagal = " + sqle.getMessage());
        }
        catch(Exception e){
           System.out.println("Koneksi Gagal " +e.getMessage());
        }
  }

public void hapus_Data() {
    ambilData_dari_JTable();
    int ok = JOptionPane.showConfirmDialog(this,
        "Anda Yakin Ingin Menghapus Data\nDengan nip = '" + txtNIP.getText() +
        "'", "Konfirmasi Menghapus Data",JOptionPane.YES_NO_OPTION);
    if (ok == 0) {
      try {
       Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
       conn=DriverManager.getConnection("jdbc:odbc:akademik_smppgri2bdg");
        String sql = "DELETE FROM guru WHERE nip = ?";
        PreparedStatement st = conn.prepareStatement(sql);
        st.setString(1, txtNIP.getText());
        int rs=st.executeUpdate();
        if(rs>0){
        tampilDataKeJTable();
        JOptionPane.showMessageDialog(this,"Data Sudah dihapus");
        }
        txtNIP.setText("");
        txtNamaGuru.setText("");
        txtTempatLahirGuru.setText("");
        dateLahirGuru.setDateFormatString("");
        CBJKGuru.setSelectedItem("");
        CBAgamaGuru.setSelectedItem("");
        CBKewarganegaraanGuru.setSelectedItem("");
        CBStatusGuru.setSelectedItem("");
        CBGolonganGuru.setSelectedItem("");
        txtNoTelpGuru.setText("");
        txtAlamatGuru.setText("");

      } catch (Exception se) {
         JOptionPane.showMessageDialog(this,"Gagal Hapus Data.. ");
       }
    }
  }

}
