/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FInputDataUser.java
 *
 * Created on 26 May 14, 19:45:38
 */

package akademik_smppgri2bdg;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asep
 */
public class FInputDataUser extends javax.swing.JFrame {
    public DefaultTableModel tabModel;
    Connection conn;

    /** Creates new form FInputDataUser */
    public FInputDataUser() {
        initComponents();
        setJTable();
        userid();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelDataUser = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        CBJabatan = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        txtUserID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtKodeMatPel = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNamaMatpel = new javax.swing.JTextField();
        txtNamaGuru = new javax.swing.JTextField();
        PanelButtonUser = new javax.swing.JPanel();
        BTambah = new javax.swing.JButton();
        BEdit = new javax.swing.JButton();
        BSimpan = new javax.swing.JButton();
        BHapus = new javax.swing.JButton();
        BBatal = new javax.swing.JButton();
        BKeluar = new javax.swing.JButton();
        PanelPencarianUSer = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        CBCariUser = new javax.swing.JComboBox();
        txtCariUser = new javax.swing.JTextField();
        BCariUser = new javax.swing.JButton();
        PanelTabelUser = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TUser = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Input Data User");

        PanelDataUser.setBackground(new java.awt.Color(204, 204, 255));
        PanelDataUser.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "DATA USER :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel4.setText("Jabatan");

        jLabel5.setText("Username");

        txtUsername.setEnabled(false);
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsernameKeyTyped(evt);
            }
        });

        jLabel23.setText("Password");

        txtPassword.setEnabled(false);
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPasswordKeyTyped(evt);
            }
        });

        CBJabatan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Pilih--", "Guru", "Kesiswaan", "Kepala Sekolah", "Admin" }));
        CBJabatan.setEnabled(false);

        jLabel24.setText("User ID");

        txtUserID.setEnabled(false);
        txtUserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserIDActionPerformed(evt);
            }
        });
        txtUserID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUserIDKeyTyped(evt);
            }
        });

        jLabel3.setText("Kode Mata Pelajaran");

        txtKodeMatPel.setEnabled(false);
        txtKodeMatPel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodeMatPelActionPerformed(evt);
            }
        });
        txtKodeMatPel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKodeMatPelKeyTyped(evt);
            }
        });

        jLabel6.setText("Nama Mata Pelajaran");

        jLabel7.setText("Nama Guru");

        txtNamaMatpel.setEnabled(false);
        txtNamaMatpel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaMatpelActionPerformed(evt);
            }
        });
        txtNamaMatpel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNamaMatpelKeyTyped(evt);
            }
        });

        txtNamaGuru.setEnabled(false);
        txtNamaGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaGuruActionPerformed(evt);
            }
        });
        txtNamaGuru.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNamaGuruKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout PanelDataUserLayout = new javax.swing.GroupLayout(PanelDataUser);
        PanelDataUser.setLayout(PanelDataUserLayout);
        PanelDataUserLayout.setHorizontalGroup(
            PanelDataUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDataUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDataUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelDataUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUserID, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                    .addComponent(txtNamaGuru, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                    .addComponent(CBJabatan, javax.swing.GroupLayout.Alignment.TRAILING, 0, 232, Short.MAX_VALUE)
                    .addComponent(txtKodeMatPel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                    .addComponent(txtNamaMatpel, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelDataUserLayout.setVerticalGroup(
            PanelDataUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDataUserLayout.createSequentialGroup()
                .addGroup(PanelDataUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDataUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDataUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDataUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CBJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDataUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKodeMatPel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDataUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNamaMatpel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDataUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNamaGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelButtonUser.setBackground(new java.awt.Color(204, 204, 255));
        PanelButtonUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelButtonUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/add.png"))); // NOI18N
        BTambah.setText("Tambah");
        BTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTambahActionPerformed(evt);
            }
        });
        PanelButtonUser.add(BTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, -1));

        BEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/edit.png"))); // NOI18N
        BEdit.setText("Edit");
        BEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEditActionPerformed(evt);
            }
        });
        PanelButtonUser.add(BEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 110, -1));

        BSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/save.png"))); // NOI18N
        BSimpan.setText("Simpan");
        BSimpan.setEnabled(false);
        BSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSimpanActionPerformed(evt);
            }
        });
        PanelButtonUser.add(BSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 110, -1));

        BHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/delete.png"))); // NOI18N
        BHapus.setText("Hapus");
        BHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHapusActionPerformed(evt);
            }
        });
        PanelButtonUser.add(BHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 110, -1));

        BBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/cancel.png"))); // NOI18N
        BBatal.setText("Batal");
        BBatal.setEnabled(false);
        BBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBatalActionPerformed(evt);
            }
        });
        PanelButtonUser.add(BBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 110, -1));

        BKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/close.png"))); // NOI18N
        BKeluar.setText("Keluar");
        BKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BKeluarActionPerformed(evt);
            }
        });
        PanelButtonUser.add(BKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 110, -1));

        PanelPencarianUSer.setBackground(new java.awt.Color(204, 204, 255));
        PanelPencarianUSer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel28.setText("Cari Berdasarkan");

        CBCariUser.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "User ID", "Username" }));

        txtCariUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariUserActionPerformed(evt);
            }
        });

        BCariUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/search.png"))); // NOI18N
        BCariUser.setText("Cari");
        BCariUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCariUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPencarianUSerLayout = new javax.swing.GroupLayout(PanelPencarianUSer);
        PanelPencarianUSer.setLayout(PanelPencarianUSerLayout);
        PanelPencarianUSerLayout.setHorizontalGroup(
            PanelPencarianUSerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPencarianUSerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addGap(6, 6, 6)
                .addComponent(CBCariUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCariUser, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BCariUser)
                .addContainerGap())
        );
        PanelPencarianUSerLayout.setVerticalGroup(
            PanelPencarianUSerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPencarianUSerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelPencarianUSerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(CBCariUser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCariUser, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BCariUser))
                .addContainerGap())
        );

        PanelTabelUser.setBackground(new java.awt.Color(204, 204, 255));
        PanelTabelUser.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "DATA TABEL USER", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        TUser.setBackground(new java.awt.Color(255, 255, 204));
        TUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TUser);

        javax.swing.GroupLayout PanelTabelUserLayout = new javax.swing.GroupLayout(PanelTabelUser);
        PanelTabelUser.setLayout(PanelTabelUserLayout);
        PanelTabelUserLayout.setHorizontalGroup(
            PanelTabelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTabelUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelTabelUserLayout.setVerticalGroup(
            PanelTabelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTabelUserLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelButtonUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PanelPencarianUSer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PanelDataUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(13, 13, 13)))
                        .addComponent(PanelTabelUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(PanelButtonUser, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelDataUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelPencarianUSer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PanelTabelUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyTyped
        // TODO add your handling code here:
}//GEN-LAST:event_txtUsernameKeyTyped

    private void BTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTambahActionPerformed
        // TODO add your handling code here:
        userid();
        txtUserID.setEnabled(false);
        txtUsername.setEnabled(true);
        txtPassword.setEnabled(true);
        CBJabatan.setEnabled(true);
        txtKodeMatPel.setEnabled(true);
        txtNamaMatpel.setEnabled(true);
        txtNamaGuru.setEnabled(true);


        BSimpan.setText("Simpan");

        BTambah.setEnabled(false);
        BSimpan.setEnabled(true);
        BEdit.setEnabled(false);
        BBatal.setEnabled(true);
        BHapus.setEnabled(false);
        BKeluar.setEnabled(false);

}//GEN-LAST:event_BTambahActionPerformed

    private void BEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEditActionPerformed
        // TODO add your handling code here:
        txtUserID.setEnabled(false);
        txtUsername.setEnabled(true);
        txtPassword.setEnabled(true);
        CBJabatan.setEnabled(true);
        txtKodeMatPel.setEnabled(true);
        txtNamaMatpel.setEnabled(true);
        txtNamaGuru.setEnabled(true);

        BSimpan.setText("Update");

        BTambah.setEnabled(false);
        BSimpan.setEnabled(true);
        BEdit.setEnabled(false);
        BBatal.setEnabled(true);
        BHapus.setEnabled(false);
        BKeluar.setEnabled(false);

        ambilData_dari_JTable();
}//GEN-LAST:event_BEditActionPerformed

    private void BSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSimpanActionPerformed
        // TODO add your handling code here:
        if(txtUserID.getText().isEmpty() ||
           txtUsername.getText().isEmpty() ||
           txtPassword.getText().isEmpty() ||
           CBJabatan.getSelectedItem().equals("--Pilih--") ||
           txtKodeMatPel.getText().isEmpty() ||
           txtNamaMatpel.getText().isEmpty() ||
           txtNamaGuru.getText().isEmpty() )
           {
            JOptionPane.showMessageDialog(this,"Data Tidak Lengkap!!");

           } else
             if(BSimpan.getText().equalsIgnoreCase("Simpan"))
                simpanData();
             else
                rubahData();

        txtUserID.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
        CBJabatan.setSelectedItem("--Pilih--");
        txtKodeMatPel.setText("");
        txtNamaMatpel.setText("");
        txtNamaGuru.setText("");

        txtUserID.setEnabled(false);
        txtUsername.setEnabled(true);
        txtPassword.setEnabled(true);
        CBJabatan.setEnabled(true);
        txtKodeMatPel.setEnabled(true);
        txtNamaMatpel.setEnabled(true);
        txtNamaGuru.setEnabled(true);

        txtUserID.setEnabled(false);
        txtUsername.setEnabled(false);
        txtPassword.setEnabled(false);
        CBJabatan.setEnabled(false);
        txtKodeMatPel.setEnabled(false);
        txtNamaMatpel.setEnabled(false);
        txtNamaGuru.setEnabled(false);

        BTambah.setEnabled(true);
        BSimpan.setEnabled(false);
        BEdit.setEnabled(true);
        BBatal.setEnabled(false);
        BHapus.setEnabled(true);
        BKeluar.setEnabled(true);

}//GEN-LAST:event_BSimpanActionPerformed

    private void BHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHapusActionPerformed
        // TODO add your handling code here:
        hapus_Data();
}//GEN-LAST:event_BHapusActionPerformed

    private void BBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBatalActionPerformed
        // TODO add your handling code here:
        txtUserID.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
        CBJabatan.setSelectedItem("--Pilih--");
        txtKodeMatPel.setText("");
        txtNamaMatpel.setText("");
        txtNamaGuru.setText("");

        txtUserID.setEnabled(false);
        txtUsername.setEnabled(false);
        txtPassword.setEnabled(false);
        CBJabatan.setEnabled(false);
        txtKodeMatPel.setEnabled(false);
        txtNamaMatpel.setEnabled(false);
        txtNamaGuru.setEnabled(false);

        BTambah.setEnabled(true);
        BSimpan.setEnabled(false);
        BEdit.setEnabled(true);
        BBatal.setEnabled(false);
        BHapus.setEnabled(true);
        BKeluar.setEnabled(true);
}//GEN-LAST:event_BBatalActionPerformed

    private void BKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BKeluarActionPerformed
        // TODO add your handling code here:
        dispose();
}//GEN-LAST:event_BKeluarActionPerformed

    private void BCariUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCariUserActionPerformed
        // TODO add your handling code here:
        String sql;
        int pilih = CBCariUser.getSelectedIndex();
        String cari = txtCariUser.getText();
        try {
            conn.close();
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            conn=DriverManager.getConnection("jdbc:odbc:akademik_smppgri2bdg");
            if(pilih==0)
                sql ="Select * from user WHERE user_id ='" +txtCariUser.getText() + "'";
            else
                sql ="Select * from user WHERE username '%" +txtCariUser.getText() + "%'";

            PreparedStatement st = conn.prepareStatement(sql);
            ResultSet rs =st.executeQuery();

            hapusIsiJTable();
            int no=0;
            while (rs.next()) {
                no++;
                String user_id = rs.getString("user_id");
                String username = rs.getString("username");
                String password = rs.getString("password");
                String jabatan = rs.getString("jabatan");
                String kode_mata_pelajaran = rs.getString("kode_mata_pelajaran");
                String nama_mata_pelajaran = rs.getString("nama_mata_pelajaran");
                String nama_guru = rs.getString("nama_guru");


                Object [] data = {no,user_id,username,password,jabatan,kode_mata_pelajaran,nama_mata_pelajaran,nama_guru};
                tabModel.addRow(data);
            }

            if(tabModel.getRowCount()>0)
                JOptionPane.showMessageDialog(this,"Data Ditemukan ");
            else
                JOptionPane.showMessageDialog(this,"Data Tidak Ditemukan.. ");

        } catch (ClassNotFoundException se) {}
        catch (SQLException se) {}
}//GEN-LAST:event_BCariUserActionPerformed

    private void txtPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyTyped
}//GEN-LAST:event_txtPasswordKeyTyped

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtUserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserIDActionPerformed
    }//GEN-LAST:event_txtUserIDActionPerformed

    private void txtUserIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserIDKeyTyped
    }//GEN-LAST:event_txtUserIDKeyTyped

    private void txtKodeMatPelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeMatPelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodeMatPelActionPerformed

    private void txtKodeMatPelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKodeMatPelKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodeMatPelKeyTyped

    private void txtNamaMatpelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaMatpelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaMatpelActionPerformed

    private void txtNamaMatpelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaMatpelKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaMatpelKeyTyped

    private void txtNamaGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaGuruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaGuruActionPerformed

    private void txtNamaGuruKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaGuruKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaGuruKeyTyped

    private void txtCariUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariUserActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FInputDataUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBatal;
    private javax.swing.JButton BCariUser;
    private javax.swing.JButton BEdit;
    private javax.swing.JButton BHapus;
    private javax.swing.JButton BKeluar;
    private javax.swing.JButton BSimpan;
    private javax.swing.JButton BTambah;
    private javax.swing.JComboBox CBCariUser;
    private javax.swing.JComboBox CBJabatan;
    private javax.swing.JPanel PanelButtonUser;
    private javax.swing.JPanel PanelDataUser;
    private javax.swing.JPanel PanelPencarianUSer;
    private javax.swing.JPanel PanelTabelUser;
    private javax.swing.JTable TUser;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCariUser;
    private javax.swing.JTextField txtKodeMatPel;
    private javax.swing.JTextField txtNamaGuru;
    private javax.swing.JTextField txtNamaMatpel;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUserID;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

     private void getData(){

  try{
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");

        conn=DriverManager.getConnection("jdbc:odbc:akademik_smppgri2bdg");

        String sql="Select * from user";
        PreparedStatement st=conn.prepareStatement(sql);

        ResultSet rs=st.executeQuery();

        String user_id,username,password,jabatan,kode_mata_pelajaran,nama_mata_pelajaran,nama_guru;
        int no=0;
        while(rs.next()){
         no=no+1;
         user_id=rs.getString("user_id");
         username=rs.getString("username");
         password=rs.getString("password");
         jabatan=rs.getString("jabatan");
         kode_mata_pelajaran = rs.getString("kode_mata_pelajaran");
         nama_mata_pelajaran = rs.getString("nama_mata_pelajaran");
         nama_guru = rs.getString("nama_guru");

         Object [] Data = {no,user_id,username,password,jabatan,kode_mata_pelajaran,nama_mata_pelajaran,nama_guru};
         tabModel.addRow(Data);
        }

          st.close();
          conn.close();
    }
    catch (ClassNotFoundException cnfe) {
           System.out.println("Class Driver tidak ditemukan.. : " + cnfe);
           System.exit(0);
    }
    catch (SQLException sqle) {
           System.out.println("Proses Query Gagal = " + sqle);
           System.exit(0);
    }
    catch(Exception e){
           System.out.println("Koneksi Access Gagal " +e.getMessage());
           System.exit(0);
    }

    }

private void setJTable(){
    String [] JudulKolom={"No","User ID","Username","Password","Jabatan","Kode Matpel","Mata Pelajaran","Guru"};
    tabModel = new DefaultTableModel(null, JudulKolom){
                  boolean[] canEdit = new boolean [] { false, false, false, false, false, false, false, false };
                  @Override
                  public boolean isCellEditable(int rowIndex, int columnIndex) {
                   return canEdit [columnIndex];
                  }
              };
    TUser.setModel(tabModel);
    TUser.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
    TUser.getColumnModel().getColumn(0).setPreferredWidth(30);
    TUser.getColumnModel().getColumn(1).setPreferredWidth(100);
    TUser.getColumnModel().getColumn(2).setPreferredWidth(100);
    TUser.getColumnModel().getColumn(3).setPreferredWidth(100);
    TUser.getColumnModel().getColumn(4).setPreferredWidth(100);
    TUser.getColumnModel().getColumn(5).setPreferredWidth(100);
    TUser.getColumnModel().getColumn(6).setPreferredWidth(100);
    TUser.getColumnModel().getColumn(7).setPreferredWidth(100);

    getData();
}

void ambilData_dari_JTable() {
    int row = TUser.getSelectedRow();

    String user_id = tabModel.getValueAt(row, 1).toString();
    String username = tabModel.getValueAt(row, 2).toString();
    String password = tabModel.getValueAt(row, 3).toString();
    String jabatan = tabModel.getValueAt(row, 4).toString();
    String kode_mata_pelajaran = tabModel.getValueAt(row, 5).toString();
    String nama_mata_pelajaran = tabModel.getValueAt(row, 6).toString();
    String nama_guru = tabModel.getValueAt(row, 7).toString();

    txtUserID.setText(user_id);
    txtUsername.setText(username);
    txtPassword.setText(password);
    CBJabatan.setSelectedItem(jabatan);
    txtKodeMatPel.setText(kode_mata_pelajaran);
    txtNamaMatpel.setText(nama_mata_pelajaran);
    txtNamaGuru.setText(nama_guru);
    }

public void hapusIsiJTable() {
    int row = tabModel.getRowCount();
    for (int i = 0; i < row; i++) {
      tabModel.removeRow(0);
    }
  }

public void tampilDataKeJTable() {
    hapusIsiJTable();
    try {
        conn.close();
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        conn=DriverManager.getConnection("jdbc:odbc:akademik_smppgri2bdg");
        String sql="Select * from user";
        PreparedStatement st=conn.prepareStatement(sql);
        ResultSet rs=st.executeQuery();
        String user_id,username,password,jabatan,kode_mata_pelajaran,nama_mata_pelajaran,nama_guru;
        int no=0;
        while(rs.next()){
         no=no+1;
         user_id=rs.getString("user_id");
         username=rs.getString("username");
         password=rs.getString("password");
         jabatan=rs.getString("jabatan");
         kode_mata_pelajaran = rs.getString("kode_mata_pelajaran");
         nama_mata_pelajaran = rs.getString("nama_mata_pelajaran");
         nama_guru = rs.getString("nama_guru");

         Object Data[]={no,user_id,username,password,jabatan,kode_mata_pelajaran,nama_mata_pelajaran,nama_guru};
         tabModel.addRow(Data);
      }
  }
    catch (Exception e) {}
}

public void rubahData() {

    int ok = JOptionPane.showConfirmDialog(this,
        "Anda Yakin Ingin Mengubah Data\n Dengan user_id = '" + txtUserID.getText() +
        "'", "Konfirmasi ",JOptionPane.YES_NO_OPTION);

    if (ok == 0) {
      try {
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        conn=DriverManager.getConnection("jdbc:odbc:akademik_smppgri2bdg");
        String sql ="UPDATE user SET username = ?,password = ?,jabatan = ? ,kode_mata_pelajaran = ?,nama_mata_pelajaran = ?,nama_guru = ? WHERE user_id = ?";
        PreparedStatement st = conn.prepareStatement(sql);
        try {
          st.setString(1, txtUsername.getText());
          st.setString(2, txtPassword.getText());
          st.setString(3, String.valueOf(CBJabatan.getSelectedItem()));
          st.setString(4, txtKodeMatPel.getText());
          st.setString(5, txtNamaMatpel.getText());
          st.setString(6, txtNamaGuru.getText());
          st.setString(7, txtUserID.getText());
          st.executeUpdate();

        tampilDataKeJTable();

        txtUserID.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
        CBJabatan.setSelectedItem("");
        txtKodeMatPel.setText("");
        txtNamaMatpel.setText("");
        txtNamaGuru.setText("");

        } catch (SQLException se) { }
      } catch (ClassNotFoundException se) {}
      catch (SQLException se) {}
    }

  }

public void simpanData(){
    try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            conn=DriverManager.getConnection("jdbc:odbc:akademik_smppgri2bdg");
            String sql="Insert into user values(?,?,?,?,?,?,?)";
            PreparedStatement st=conn.prepareStatement(sql);
                st.setString(1, txtUserID.getText());
                st.setString(2, txtUsername.getText());
                st.setString(3, txtPassword.getText());
                st.setString(4, String.valueOf(CBJabatan.getSelectedItem()));
                st.setString(5, txtKodeMatPel.getText());
                st.setString(6, txtNamaMatpel.getText());
                st.setString(7, txtNamaGuru.getText());
            int rs=st.executeUpdate();

            if(rs>0){
            JOptionPane.showMessageDialog(this,"Input Berhasil");
      	    tampilDataKeJTable();
            }
            st.close();
            conn.close();
        }
        catch (ClassNotFoundException cnfe) {
           System.out.println("Class Driver tidak ditemukan.. : " + cnfe);
        }
        catch (SQLException sqle) {
           System.out.println("Input  Gagal = " + sqle.getMessage());
        }
        catch(Exception e){
           System.out.println("Koneksi Gagal " +e.getMessage());
        }
  }

public void hapus_Data() {
    ambilData_dari_JTable();
    int ok = JOptionPane.showConfirmDialog(this,
        "Anda Yakin Ingin Menghapus Data\nDengan user = '" + txtUserID.getText() +
        "'", "Konfirmasi Menghapus Data",JOptionPane.YES_NO_OPTION);
    if (ok == 0) {
      try {
       Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
       conn=DriverManager.getConnection("jdbc:odbc:akademik_smppgri2bdg");
        String sql = "DELETE FROM user WHERE user_id = ?";
        PreparedStatement st = conn.prepareStatement(sql);
        st.setString(1, txtUserID.getText());
        int rs=st.executeUpdate();
        if(rs>0){
        tampilDataKeJTable();
        JOptionPane.showMessageDialog(this,"Data Sudah dihapus");
        }
        txtUserID.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
        CBJabatan.setSelectedItem("");
        txtKodeMatPel.setText("");
        txtNamaMatpel.setText("");
        txtNamaGuru.setText("");
      } catch (Exception se) {
         JOptionPane.showMessageDialog(this,"Gagal Hapus Data.. ");
       }
    }
  }
private void userid(){

        try{

            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            conn=DriverManager.getConnection("jdbc:odbc:akademik_smppgri2bdg");
            String sql="select * from user";
            PreparedStatement st=conn.prepareStatement(sql);
            ResultSet rs=st.executeQuery();
            while(rs.next()){

            String no;

            no = rs.getString(1);


                int n = Integer.parseInt(no.substring(5,7))+1;
                String nomor="0";
                for(int i = 1; i <= 2 - String.valueOf(n).length();i++)
                {
                    nomor = nomor + "0";
                }
                nomor = "2013" + nomor + String.valueOf(n);
                txtUserID.setText(nomor);
            }

            st.close();
            conn.close();
        }
        catch (ClassNotFoundException cnfe) {
           System.out.println("Class Driver tidak ditemukan.. : " + cnfe);
        }
        catch (SQLException sqle) {
           System.out.println("Input  Gagal = " + sqle.getMessage());
        }
        catch(Exception e){
           System.out.println("Koneksi Gagal " +e.getMessage());
        }

    }
}
