/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FInputDataMataPelajaran.java
 *
 * Created on 26 May 14, 19:45:38
 */

package akademik_smppgri2bdg;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asep
 */
public class FInputDataMataPelajaran extends javax.swing.JFrame {
    public DefaultTableModel tabModel;
    Connection conn;

    /** Creates new form FInputDataMataPelajaran */
    public FInputDataMataPelajaran() {
        initComponents();
        setJTable();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelDataMatpel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtKodeMatpel = new javax.swing.JTextField();
        txtNamaMatpel = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtJamMatpel = new javax.swing.JTextField();
        PanelTabelMatpel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TMatpel = new javax.swing.JTable();
        PanelPencarianMatpel = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        CBCariMatpel = new javax.swing.JComboBox();
        txtCariMatpel = new javax.swing.JTextField();
        BCariMatpel = new javax.swing.JButton();
        PanelButtonMatpel = new javax.swing.JPanel();
        BTambah = new javax.swing.JButton();
        BEdit = new javax.swing.JButton();
        BSimpan = new javax.swing.JButton();
        BHapus = new javax.swing.JButton();
        BBatal = new javax.swing.JButton();
        BKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Input Data Mata Pelajaran");

        PanelDataMatpel.setBackground(new java.awt.Color(204, 204, 255));
        PanelDataMatpel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "DATA MATA PELAJARAN :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel4.setText("Kode Mata Pelajaran");

        jLabel5.setText("Nama Mata Pelajaran");

        txtKodeMatpel.setEnabled(false);
        txtKodeMatpel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodeMatpelActionPerformed(evt);
            }
        });

        txtNamaMatpel.setEnabled(false);
        txtNamaMatpel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNamaMatpelKeyTyped(evt);
            }
        });

        jLabel23.setText("Jumlah Jam Pelajaran");

        txtJamMatpel.setEnabled(false);
        txtJamMatpel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtJamMatpelKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout PanelDataMatpelLayout = new javax.swing.GroupLayout(PanelDataMatpel);
        PanelDataMatpel.setLayout(PanelDataMatpelLayout);
        PanelDataMatpelLayout.setHorizontalGroup(
            PanelDataMatpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDataMatpelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDataMatpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(PanelDataMatpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtJamMatpel)
                    .addComponent(txtKodeMatpel, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(txtNamaMatpel, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        PanelDataMatpelLayout.setVerticalGroup(
            PanelDataMatpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDataMatpelLayout.createSequentialGroup()
                .addGroup(PanelDataMatpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKodeMatpel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDataMatpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaMatpel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDataMatpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtJamMatpel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelTabelMatpel.setBackground(new java.awt.Color(204, 204, 255));
        PanelTabelMatpel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "DATA TABEL GURU", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        TMatpel.setBackground(new java.awt.Color(255, 255, 204));
        TMatpel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TMatpel);

        javax.swing.GroupLayout PanelTabelMatpelLayout = new javax.swing.GroupLayout(PanelTabelMatpel);
        PanelTabelMatpel.setLayout(PanelTabelMatpelLayout);
        PanelTabelMatpelLayout.setHorizontalGroup(
            PanelTabelMatpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTabelMatpelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelTabelMatpelLayout.setVerticalGroup(
            PanelTabelMatpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTabelMatpelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelPencarianMatpel.setBackground(new java.awt.Color(204, 204, 255));
        PanelPencarianMatpel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel28.setText("Cari Berdasarkan");

        CBCariMatpel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kode Matpel", "Nama Matpel" }));
        CBCariMatpel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBCariMatpelActionPerformed(evt);
            }
        });

        BCariMatpel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/search.png"))); // NOI18N
        BCariMatpel.setText("Cari");
        BCariMatpel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCariMatpelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPencarianMatpelLayout = new javax.swing.GroupLayout(PanelPencarianMatpel);
        PanelPencarianMatpel.setLayout(PanelPencarianMatpelLayout);
        PanelPencarianMatpelLayout.setHorizontalGroup(
            PanelPencarianMatpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPencarianMatpelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addGap(6, 6, 6)
                .addComponent(CBCariMatpel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCariMatpel, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BCariMatpel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelPencarianMatpelLayout.setVerticalGroup(
            PanelPencarianMatpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPencarianMatpelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelPencarianMatpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(CBCariMatpel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCariMatpel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BCariMatpel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        PanelButtonMatpel.setBackground(new java.awt.Color(204, 204, 255));
        PanelButtonMatpel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelButtonMatpel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/add.png"))); // NOI18N
        BTambah.setText("Tambah");
        BTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTambahActionPerformed(evt);
            }
        });
        PanelButtonMatpel.add(BTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, -1));

        BEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/edit.png"))); // NOI18N
        BEdit.setText("Edit");
        BEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEditActionPerformed(evt);
            }
        });
        PanelButtonMatpel.add(BEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 110, -1));

        BSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/save.png"))); // NOI18N
        BSimpan.setText("Simpan");
        BSimpan.setEnabled(false);
        BSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSimpanActionPerformed(evt);
            }
        });
        PanelButtonMatpel.add(BSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 120, -1));

        BHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/delete.png"))); // NOI18N
        BHapus.setText("Hapus");
        BHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHapusActionPerformed(evt);
            }
        });
        PanelButtonMatpel.add(BHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 110, 30));

        BBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/cancel.png"))); // NOI18N
        BBatal.setText("Batal");
        BBatal.setEnabled(false);
        BBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBatalActionPerformed(evt);
            }
        });
        PanelButtonMatpel.add(BBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 110, -1));

        BKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/close.png"))); // NOI18N
        BKeluar.setText("Keluar");
        BKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BKeluarActionPerformed(evt);
            }
        });
        PanelButtonMatpel.add(BKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelButtonMatpel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PanelDataMatpel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanelPencarianMatpel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PanelTabelMatpel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelButtonMatpel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelDataMatpel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PanelPencarianMatpel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PanelTabelMatpel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaMatpelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaMatpelKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (((c >= '0') && (c <= '9') && txtNamaMatpel.getText().length() < 50
                || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
}//GEN-LAST:event_txtNamaMatpelKeyTyped

    private void txtJamMatpelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJamMatpelKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') && txtJamMatpel.getText().length() < 15
                || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
}//GEN-LAST:event_txtJamMatpelKeyTyped

    private void BCariMatpelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCariMatpelActionPerformed
        // TODO add your handling code here:
        String sql;
        int pilih = CBCariMatpel.getSelectedIndex();
        String cari = txtCariMatpel.getText();
        try {
            conn.close();
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            conn=DriverManager.getConnection("jdbc:odbc:akademik_smppgri2bdg");
            if(pilih==0)
                sql ="Select * from mata_pelajaran WHERE kode_mata_pelajaran ='" +txtCariMatpel.getText() + "'";
            else
                sql ="Select * from mata_pelajaran WHERE nama_mata_pelajaran Like '%" +txtCariMatpel.getText() + "%'";

            PreparedStatement st = conn.prepareStatement(sql);
            ResultSet rs =st.executeQuery();

            hapusIsiJTable();
            int no=0;
            while (rs.next()) {
                no++;
                String kode_mata_pelajaran = rs.getString("kode_mata_pelajaran");
                String nama_mata_pelajaran = rs.getString("nama_mata_pelajaran");
                String jam_mata_pelajaran = rs.getString("jam_mata_pelajaran");
                
                Object [] data = {no,kode_mata_pelajaran,nama_mata_pelajaran,jam_mata_pelajaran};
                tabModel.addRow(data);
            }

            if(tabModel.getRowCount()>0)
                JOptionPane.showMessageDialog(this,"Data Ditemukan ");
            else
                JOptionPane.showMessageDialog(this,"Data Tidak Ditemukan.. ");

        } catch (ClassNotFoundException se) {}
        catch (SQLException se) {}
}//GEN-LAST:event_BCariMatpelActionPerformed

    private void BTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTambahActionPerformed
        // TODO add your handling code here:
        txtKodeMatpel.setEnabled(true);
        txtNamaMatpel.setEnabled(true);
        txtJamMatpel.setEnabled(true);
        
        BSimpan.setText("Simpan");

        BTambah.setEnabled(false);
        BSimpan.setEnabled(true);
        BEdit.setEnabled(false);
        BBatal.setEnabled(true);
        BHapus.setEnabled(false);
        BKeluar.setEnabled(false);

}//GEN-LAST:event_BTambahActionPerformed

    private void BEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEditActionPerformed
        // TODO add your handling code here:
        txtKodeMatpel.setEnabled(false);
        txtNamaMatpel.setEnabled(true);
        txtJamMatpel.setEnabled(true);
        
        BSimpan.setText("Update");

        BTambah.setEnabled(false);
        BSimpan.setEnabled(true);
        BEdit.setEnabled(false);
        BBatal.setEnabled(true);
        BHapus.setEnabled(false);
        BKeluar.setEnabled(false);


        ambilData_dari_JTable();
}//GEN-LAST:event_BEditActionPerformed

    private void BSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSimpanActionPerformed
        // TODO add your handling code here:
        if(txtKodeMatpel.getText().isEmpty() ||
           txtNamaMatpel.getText().isEmpty() ||
           txtJamMatpel.getText().isEmpty() )
           {
            JOptionPane.showMessageDialog(this,"Data Tidak Lengkap!!");

           } else
             if(BSimpan.getText().equalsIgnoreCase("Simpan"))
                simpanData();
             else
                rubahData();

        txtKodeMatpel.setText("");
        txtNamaMatpel.setText("");
        txtJamMatpel.setText("");
        
        txtKodeMatpel.setEnabled(false);
        txtNamaMatpel.setEnabled(true);
        txtJamMatpel.setEnabled(true);
        
        txtKodeMatpel.setEnabled(false);
        txtNamaMatpel.setEnabled(false);
        txtJamMatpel.setEnabled(false);
        
        BTambah.setEnabled(true);
        BSimpan.setEnabled(false);
        BEdit.setEnabled(true);
        BBatal.setEnabled(false);
        BHapus.setEnabled(true);
        BKeluar.setEnabled(true);
}//GEN-LAST:event_BSimpanActionPerformed

    private void BHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHapusActionPerformed
        // TODO add your handling code here:
        hapus_Data();
}//GEN-LAST:event_BHapusActionPerformed

    private void BBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBatalActionPerformed
        // TODO add your handling code here:
        txtKodeMatpel.setText("");
        txtNamaMatpel.setText("");
        txtJamMatpel.setText("");
        
        txtKodeMatpel.setEnabled(false);
        txtNamaMatpel.setEnabled(false);
        txtJamMatpel.setEnabled(false);

        BTambah.setEnabled(true);
        BSimpan.setEnabled(false);
        BEdit.setEnabled(true);
        BBatal.setEnabled(false);
        BHapus.setEnabled(true);
        BKeluar.setEnabled(true);
}//GEN-LAST:event_BBatalActionPerformed

    private void BKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BKeluarActionPerformed
        // TODO add your handling code here:
        dispose();
}//GEN-LAST:event_BKeluarActionPerformed

    private void txtKodeMatpelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeMatpelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodeMatpelActionPerformed

    private void CBCariMatpelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBCariMatpelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBCariMatpelActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FInputDataMataPelajaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBatal;
    private javax.swing.JButton BCariMatpel;
    private javax.swing.JButton BEdit;
    private javax.swing.JButton BHapus;
    private javax.swing.JButton BKeluar;
    private javax.swing.JButton BSimpan;
    private javax.swing.JButton BTambah;
    private javax.swing.JComboBox CBCariMatpel;
    private javax.swing.JPanel PanelButtonMatpel;
    private javax.swing.JPanel PanelDataMatpel;
    private javax.swing.JPanel PanelPencarianMatpel;
    private javax.swing.JPanel PanelTabelMatpel;
    private javax.swing.JTable TMatpel;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCariMatpel;
    private javax.swing.JTextField txtJamMatpel;
    private javax.swing.JTextField txtKodeMatpel;
    private javax.swing.JTextField txtNamaMatpel;
    // End of variables declaration//GEN-END:variables

    private void getData(){

  try{
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");

        conn=DriverManager.getConnection("jdbc:odbc:akademik_smppgri2bdg");

        String sql="Select * from mata_pelajaran";
        PreparedStatement st=conn.prepareStatement(sql);

        ResultSet rs=st.executeQuery();

        String kode_mata_pelajaran,nama_mata_pelajaran,jam_mata_pelajaran;
        int no=0;
        while(rs.next()){
         no=no+1;
         kode_mata_pelajaran=rs.getString("kode_mata_pelajaran");
         nama_mata_pelajaran=rs.getString("nama_mata_pelajaran");
         jam_mata_pelajaran=rs.getString("jam_mata_pelajaran");
         Object [] Data = {no,kode_mata_pelajaran,nama_mata_pelajaran,jam_mata_pelajaran};
         tabModel.addRow(Data);
        }

          st.close();
          conn.close();
    }
    catch (ClassNotFoundException cnfe) {
           System.out.println("Class Driver tidak ditemukan.. : " + cnfe);
           System.exit(0);
    }
    catch (SQLException sqle) {
           System.out.println("Proses Query Gagal = " + sqle);
           System.exit(0);
    }
    catch(Exception e){
           System.out.println("Koneksi Access Gagal " +e.getMessage());
           System.exit(0);
    }

    }

private void setJTable(){
    String [] JudulKolom={"No","Kode Mata Pelajaran","Nama Mata Pelajaran","Jumlah Jam Pelajaran"};
    tabModel = new DefaultTableModel(null, JudulKolom){
                  boolean[] canEdit = new boolean [] { false, false, false, false };
                  @Override
                  public boolean isCellEditable(int rowIndex, int columnIndex) {
                   return canEdit [columnIndex];
                  }
              };
    TMatpel.setModel(tabModel);
    TMatpel.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
    TMatpel.getColumnModel().getColumn(0).setPreferredWidth(30);
    TMatpel.getColumnModel().getColumn(1).setPreferredWidth(150);
    TMatpel.getColumnModel().getColumn(2).setPreferredWidth(150);
    TMatpel.getColumnModel().getColumn(3).setPreferredWidth(150);
    
    getData();
}

void ambilData_dari_JTable() {
    int row = TMatpel.getSelectedRow();

    String kode_mata_pelajaran = tabModel.getValueAt(row, 1).toString();
    String nama_mata_pelajaran = tabModel.getValueAt(row, 2).toString();
    String jam_mata_pelajaran = tabModel.getValueAt(row, 3).toString();
   
    txtKodeMatpel.setText(kode_mata_pelajaran);
    txtNamaMatpel.setText(nama_mata_pelajaran);
    txtJamMatpel.setText(jam_mata_pelajaran);
   
    }

public void hapusIsiJTable() {
    int row = tabModel.getRowCount();
    for (int i = 0; i < row; i++) {
      tabModel.removeRow(0);
    }
  }

public void tampilDataKeJTable() {
    hapusIsiJTable();
    try {
        conn.close();
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        conn=DriverManager.getConnection("jdbc:odbc:akademik_smppgri2bdg");
        String sql="Select * from mata_pelajaran";
        PreparedStatement st=conn.prepareStatement(sql);
        ResultSet rs=st.executeQuery();
        String kode_mata_pelajaran,nama_mata_pelajaran,jam_mata_pelajaran;
        int no=0;
        while(rs.next()){
         no=no+1;
         kode_mata_pelajaran=rs.getString("kode_mata_pelajaran");
         nama_mata_pelajaran=rs.getString("nama_mata_pelajaran");
         jam_mata_pelajaran=rs.getString("jam_mata_pelajaran");
         
         Object Data[]={no,kode_mata_pelajaran,nama_mata_pelajaran,jam_mata_pelajaran};
         tabModel.addRow(Data);
      }
  }
    catch (Exception e) {}
}

public void rubahData() {

    int ok = JOptionPane.showConfirmDialog(this,
        "Anda Yakin Ingin Mengubah Data\n Dengan Kode Mata Pelajaran = '" + txtKodeMatpel.getText() +
        "'", "Konfirmasi ",JOptionPane.YES_NO_OPTION);

    if (ok == 0) {
      try {
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        conn=DriverManager.getConnection("jdbc:odbc:akademik_smppgri2bdg");
        String sql ="UPDATE mata_pelajaran SET nama_mata_pelajaran = ?,jam_mata_pelajaran = ? WHERE kode_mata_pelajaran = ?";
        PreparedStatement st = conn.prepareStatement(sql);
        try {
          st.setString(1, txtNamaMatpel.getText());
          st.setString(2, txtJamMatpel.getText());
          st.setString(3, txtKodeMatpel.getText());
          st.executeUpdate();

        tampilDataKeJTable();

        txtKodeMatpel.setText("");
        txtNamaMatpel.setText("");
        txtJamMatpel.setText("");
        } catch (SQLException se) { }
      } catch (ClassNotFoundException se) {}
      catch (SQLException se) {}
    }

  }

public void simpanData(){
    try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            conn=DriverManager.getConnection("jdbc:odbc:akademik_smppgri2bdg");
            String sql="Insert into mata_pelajaran values(?,?,?)";
            PreparedStatement st=conn.prepareStatement(sql);
                st.setString(1, txtKodeMatpel.getText());
                st.setString(2, txtNamaMatpel.getText());
                st.setString(3, txtJamMatpel.getText());
            int rs=st.executeUpdate();

            if(rs>0){
            JOptionPane.showMessageDialog(this,"Input Berhasil");
      	    tampilDataKeJTable();
            }
            st.close();
            conn.close();
        }
        catch (ClassNotFoundException cnfe) {
           System.out.println("Class Driver tidak ditemukan.. : " + cnfe);
        }
        catch (SQLException sqle) {
           System.out.println("Input  Gagal = " + sqle.getMessage());
        }
        catch(Exception e){
           System.out.println("Koneksi Gagal " +e.getMessage());
        }
  }

public void hapus_Data() {
    ambilData_dari_JTable();
    int ok = JOptionPane.showConfirmDialog(this,
        "Anda Yakin Ingin Menghapus Data\nDengan kode_mata_pelajaran = '" + txtKodeMatpel.getText() +
        "'", "Konfirmasi Menghapus Data",JOptionPane.YES_NO_OPTION);
    if (ok == 0) {
      try {
       Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
       conn=DriverManager.getConnection("jdbc:odbc:akademik_smppgri2bdg");
        String sql = "DELETE FROM mata_pelajaran WHERE kode_mata_pelajaran = ?";
        PreparedStatement st = conn.prepareStatement(sql);
        st.setString(1, txtKodeMatpel.getText());
        int rs=st.executeUpdate();
        if(rs>0){
        tampilDataKeJTable();
        JOptionPane.showMessageDialog(this,"Data Sudah dihapus");
        }
        txtKodeMatpel.setText("");
        txtNamaMatpel.setText("");
        txtJamMatpel.setText("");        
      } catch (Exception se) {
         JOptionPane.showMessageDialog(this,"Gagal Hapus Data.. ");
       }
    }
  }
}
