/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FPembagianWaliKelas.java
 *
 * Created on 30 Jun 13, 19:45:38
 */

package akademik_smppgri2bdg;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author syadam
 */
public class FPembagianWaliKelas extends javax.swing.JFrame {
    public DefaultTableModel tabModel;
    Connection conn;

    /** Creates new form FPembagianWaliKelas */
    public FPembagianWaliKelas() {
        initComponents();
        setJTable();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        PanelDataWaliKelas = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        CBKelas = new javax.swing.JComboBox();
        txtStatusWaliKelas = new javax.swing.JTextField();
        txtGolonganWaliKelas = new javax.swing.JTextField();
        txtNamaWaliKelas = new javax.swing.JTextField();
        PanelTabelWaliKelas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TWaliKelas = new javax.swing.JTable();
        PanelButtonWaliKelas = new javax.swing.JPanel();
        BTambah = new javax.swing.JButton();
        BEdit = new javax.swing.JButton();
        BSimpan = new javax.swing.JButton();
        BHapus = new javax.swing.JButton();
        BBatal = new javax.swing.JButton();
        BKeluar = new javax.swing.JButton();
        PanelPencarianWaliKelas = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        CBCariWaliKelas = new javax.swing.JComboBox();
        txtCariWaliKelas = new javax.swing.JTextField();
        BCariWaliKelas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Pembagian Wali Kelas");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("PEMBAGIAN WALI KELAS");

        PanelDataWaliKelas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel4.setText("Kelas");

        jLabel5.setText("Nama Wali Kelas");

        jLabel21.setText("Status");

        jLabel22.setText("Golongan");

        CBKelas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Pilih--", "X 1", "X 2", "X 3", "X 4", "X 5" }));
        CBKelas.setEnabled(false);

        txtStatusWaliKelas.setEnabled(false);
        txtStatusWaliKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStatusWaliKelasActionPerformed(evt);
            }
        });
        txtStatusWaliKelas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStatusWaliKelasKeyTyped(evt);
            }
        });

        txtGolonganWaliKelas.setEnabled(false);
        txtGolonganWaliKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGolonganWaliKelasActionPerformed(evt);
            }
        });
        txtGolonganWaliKelas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGolonganWaliKelasKeyTyped(evt);
            }
        });

        txtNamaWaliKelas.setEnabled(false);
        txtNamaWaliKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaWaliKelasActionPerformed(evt);
            }
        });
        txtNamaWaliKelas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNamaWaliKelasKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNamaWaliKelasKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout PanelDataWaliKelasLayout = new javax.swing.GroupLayout(PanelDataWaliKelas);
        PanelDataWaliKelas.setLayout(PanelDataWaliKelasLayout);
        PanelDataWaliKelasLayout.setHorizontalGroup(
            PanelDataWaliKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDataWaliKelasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDataWaliKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addGap(20, 20, 20)
                .addGroup(PanelDataWaliKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDataWaliKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtStatusWaliKelas, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtGolonganWaliKelas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                    .addComponent(CBKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaWaliKelas, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelDataWaliKelasLayout.setVerticalGroup(
            PanelDataWaliKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDataWaliKelasLayout.createSequentialGroup()
                .addGroup(PanelDataWaliKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CBKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDataWaliKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNamaWaliKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDataWaliKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtStatusWaliKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDataWaliKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtGolonganWaliKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        PanelTabelWaliKelas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "DATA TABEL WALI KELAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        TWaliKelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TWaliKelas);

        javax.swing.GroupLayout PanelTabelWaliKelasLayout = new javax.swing.GroupLayout(PanelTabelWaliKelas);
        PanelTabelWaliKelas.setLayout(PanelTabelWaliKelasLayout);
        PanelTabelWaliKelasLayout.setHorizontalGroup(
            PanelTabelWaliKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTabelWaliKelasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelTabelWaliKelasLayout.setVerticalGroup(
            PanelTabelWaliKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTabelWaliKelasLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelButtonWaliKelas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelButtonWaliKelas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTambah.setText("Tambah");
        BTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTambahActionPerformed(evt);
            }
        });
        PanelButtonWaliKelas.add(BTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, -1));

        BEdit.setText("Edit");
        BEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEditActionPerformed(evt);
            }
        });
        PanelButtonWaliKelas.add(BEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 80, -1));

        BSimpan.setText("Simpan");
        BSimpan.setEnabled(false);
        BSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSimpanActionPerformed(evt);
            }
        });
        PanelButtonWaliKelas.add(BSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 80, -1));

        BHapus.setText("Hapus");
        BHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHapusActionPerformed(evt);
            }
        });
        PanelButtonWaliKelas.add(BHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 80, -1));

        BBatal.setText("Batal");
        BBatal.setEnabled(false);
        BBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBatalActionPerformed(evt);
            }
        });
        PanelButtonWaliKelas.add(BBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 80, -1));

        BKeluar.setText("Keluar");
        BKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BKeluarActionPerformed(evt);
            }
        });
        PanelButtonWaliKelas.add(BKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 80, -1));

        PanelPencarianWaliKelas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel28.setText("Cari Berdasarkan");

        CBCariWaliKelas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kelas", "Wali Kelas" }));
        CBCariWaliKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBCariWaliKelasActionPerformed(evt);
            }
        });

        BCariWaliKelas.setText("Cari");
        BCariWaliKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCariWaliKelasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPencarianWaliKelasLayout = new javax.swing.GroupLayout(PanelPencarianWaliKelas);
        PanelPencarianWaliKelas.setLayout(PanelPencarianWaliKelasLayout);
        PanelPencarianWaliKelasLayout.setHorizontalGroup(
            PanelPencarianWaliKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPencarianWaliKelasLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel28)
                .addGap(6, 6, 6)
                .addComponent(CBCariWaliKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCariWaliKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BCariWaliKelas, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelPencarianWaliKelasLayout.setVerticalGroup(
            PanelPencarianWaliKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPencarianWaliKelasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelPencarianWaliKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(CBCariWaliKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCariWaliKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BCariWaliKelas))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelButtonWaliKelas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PanelDataWaliKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelTabelWaliKelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanelPencarianWaliKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jLabel2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(PanelTabelWaliKelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(PanelPencarianWaliKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelDataWaliKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelButtonWaliKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTambahActionPerformed
        // TODO add your handling code here:
        CBKelas.setEnabled(true);
        txtNamaWaliKelas.setEnabled(true);
        txtStatusWaliKelas.setEnabled(false);
        txtGolonganWaliKelas.setEnabled(false);
        
        BSimpan.setText("Simpan");

        BTambah.setEnabled(false);
        BSimpan.setEnabled(true);
        BEdit.setEnabled(false);
        BBatal.setEnabled(true);
        BHapus.setEnabled(false);
        BKeluar.setEnabled(false);

}//GEN-LAST:event_BTambahActionPerformed

    private void BEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEditActionPerformed
        // TODO add your handling code here:
        
        CBKelas.setEnabled(false);
        txtNamaWaliKelas.setEnabled(true);
        txtStatusWaliKelas.setEnabled(false);
        txtGolonganWaliKelas.setEnabled(false);

        BSimpan.setText("Update");

        BTambah.setEnabled(false);
        BSimpan.setEnabled(true);
        BEdit.setEnabled(false);
        BBatal.setEnabled(true);
        BHapus.setEnabled(false);
        BKeluar.setEnabled(false);


        ambilData_dari_JTable();
}//GEN-LAST:event_BEditActionPerformed

    private void BSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSimpanActionPerformed
        // TODO add your handling code here:
       if(CBKelas.getSelectedItem().equals("--Pilih--") ||
          txtNamaWaliKelas.getText().isEmpty()  ||
          txtStatusWaliKelas.getText().isEmpty()  ||
          txtStatusWaliKelas.getText().isEmpty())
           {
            JOptionPane.showMessageDialog(this,"Data Tidak Lengkap!!");

           } else
             if(BSimpan.getText().equalsIgnoreCase("Simpan"))
                simpanData();
             else
                rubahData();

        CBKelas.setSelectedItem("--Pilih--");
        txtNamaWaliKelas.setText("");
        txtStatusWaliKelas.setText("");
        txtGolonganWaliKelas.setText("");
        
        CBKelas.setEnabled(false);
        txtNamaWaliKelas.setEnabled(true);
        txtStatusWaliKelas.setEnabled(true);
        txtGolonganWaliKelas.setEnabled(true);

        CBKelas.setEnabled(false);
        txtNamaWaliKelas.setEnabled(false);
        txtStatusWaliKelas.setEnabled(false);
        txtGolonganWaliKelas.setEnabled(false);
        
        BTambah.setEnabled(true);
        BSimpan.setEnabled(false);
        BEdit.setEnabled(true);
        BBatal.setEnabled(false);
        BHapus.setEnabled(true);
        BKeluar.setEnabled(true);
}//GEN-LAST:event_BSimpanActionPerformed

    private void BHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHapusActionPerformed
        // TODO add your handling code here:
        hapus_Data();
}//GEN-LAST:event_BHapusActionPerformed

    private void BBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBatalActionPerformed
        // TODO add your handling code here:
        CBKelas.setSelectedItem("");
        txtNamaWaliKelas.setText("");
        txtStatusWaliKelas.setText("");
        txtGolonganWaliKelas.setText("");

        CBKelas.setEnabled(false);
        txtNamaWaliKelas.setEnabled(false);
        txtStatusWaliKelas.setEnabled(false);
        txtGolonganWaliKelas.setEnabled(false);

        BTambah.setEnabled(true);
        BSimpan.setEnabled(false);
        BEdit.setEnabled(true);
        BBatal.setEnabled(false);
        BHapus.setEnabled(true);
        BKeluar.setEnabled(true);
}//GEN-LAST:event_BBatalActionPerformed

    private void BKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BKeluarActionPerformed
        // TODO add your handling code here:
        dispose();
}//GEN-LAST:event_BKeluarActionPerformed

    private void BCariWaliKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCariWaliKelasActionPerformed
        // TODO add your handling code here:
        String sql;
        int pilih = CBCariWaliKelas.getSelectedIndex();
        String cari = txtCariWaliKelas.getText();
        try {
            conn.close();
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            conn=DriverManager.getConnection("jdbc:odbc:akademik_smppgri2bdg");
            if(pilih==0)
                sql ="Select * from wali_kelas WHERE kelas ='" +txtCariWaliKelas.getText() + "'";
            else
                sql ="Select * from wali_kelas WHERE nama_guru Like '%" +txtCariWaliKelas.getText() + "%'";

            PreparedStatement st = conn.prepareStatement(sql);
            ResultSet rs =st.executeQuery();

            hapusIsiJTable();
            int no=0;
            while (rs.next()) {
                no++;
                String kelas = rs.getString("kelas");
                String nama_guru = rs.getString("nama_guru");
                String status_guru = rs.getString("status_guru");
                String golongan_guru = rs.getString("golongan_guru");
                
                Object [] data = {no,kelas,nama_guru,status_guru,golongan_guru};
                tabModel.addRow(data);
            }

            if(tabModel.getRowCount()>0)
                JOptionPane.showMessageDialog(this,"Data Ditemukan ");
            else
                JOptionPane.showMessageDialog(this,"Data Tidak Ditemukan.. ");

        } catch (ClassNotFoundException se) {} catch (SQLException se) {}
}//GEN-LAST:event_BCariWaliKelasActionPerformed

    private void CBCariWaliKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBCariWaliKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBCariWaliKelasActionPerformed

    private void txtStatusWaliKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStatusWaliKelasActionPerformed

}//GEN-LAST:event_txtStatusWaliKelasActionPerformed

    private void txtStatusWaliKelasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStatusWaliKelasKeyTyped
        // TODO add your handling code here:
}//GEN-LAST:event_txtStatusWaliKelasKeyTyped

    private void txtGolonganWaliKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGolonganWaliKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGolonganWaliKelasActionPerformed

    private void txtGolonganWaliKelasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGolonganWaliKelasKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGolonganWaliKelasKeyTyped

    private void txtNamaWaliKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaWaliKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaWaliKelasActionPerformed

    private void txtNamaWaliKelasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaWaliKelasKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNamaWaliKelasKeyTyped

    private void txtNamaWaliKelasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaWaliKelasKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
        try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            conn=DriverManager.getConnection("jdbc:odbc:akademik_smppgri2bdg");
            String sql="select * from guru where nama_guru='"+txtNamaWaliKelas.getText()+"'";
            PreparedStatement st=conn.prepareStatement(sql);
            ResultSet rs=st.executeQuery();
            int no=0+1;
            while(rs.next()){
                txtStatusWaliKelas.setText(rs.getString("status_guru"));
                txtGolonganWaliKelas.setText(rs.getString("golongan_guru"));


            }

            st.close();
            conn.close();

        } catch (ClassNotFoundException cnfe) {
            System.out.println("Class Driver tidak ditemukan.. : " + cnfe);
            System.exit(0);
        } catch (SQLException sqle) {
            System.out.println("Proses Query Gagal = " + sqle);
            System.exit(0);
        } catch(Exception e){
            System.out.println("Koneksi Access Gagal " +e.getMessage());
            System.exit(0);
        }
        }
    }//GEN-LAST:event_txtNamaWaliKelasKeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FPembagianWaliKelas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBatal;
    private javax.swing.JButton BCariWaliKelas;
    private javax.swing.JButton BEdit;
    private javax.swing.JButton BHapus;
    private javax.swing.JButton BKeluar;
    private javax.swing.JButton BSimpan;
    private javax.swing.JButton BTambah;
    private javax.swing.JComboBox CBCariWaliKelas;
    private javax.swing.JComboBox CBKelas;
    private javax.swing.JPanel PanelButtonWaliKelas;
    private javax.swing.JPanel PanelDataWaliKelas;
    private javax.swing.JPanel PanelPencarianWaliKelas;
    private javax.swing.JPanel PanelTabelWaliKelas;
    private javax.swing.JTable TWaliKelas;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCariWaliKelas;
    private javax.swing.JTextField txtGolonganWaliKelas;
    private javax.swing.JTextField txtNamaWaliKelas;
    private javax.swing.JTextField txtStatusWaliKelas;
    // End of variables declaration//GEN-END:variables

  private void getData(){

  try{
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");

        conn=DriverManager.getConnection("jdbc:odbc:akademik_smppgri2bdg");

        String sql="Select * from wali_kelas";
        PreparedStatement st=conn.prepareStatement(sql);

        ResultSet rs=st.executeQuery();

        String kelas,nama_guru,status_guru,golongan_guru;
        int no=0;
        while(rs.next()){
         no=no+1;
         kelas=rs.getString("kelas");
         nama_guru=rs.getString("nama_guru");
         status_guru=rs.getString("status_guru");
         golongan_guru=rs.getString("golongan_guru");
         Object [] Data = {no,kelas,nama_guru,status_guru,golongan_guru};
         tabModel.addRow(Data);
        }

          st.close();
          conn.close();
    }
    catch (ClassNotFoundException cnfe) {
           System.out.println("Class Driver tidak ditemukan.. : " + cnfe);
           System.exit(0);
    }
    catch (SQLException sqle) {
           System.out.println("Proses Query Gagal = " + sqle);
           System.exit(0);
    }
    catch(Exception e){
           System.out.println("Koneksi Access Gagal " +e.getMessage());
           System.exit(0);
    }

    }

private void setJTable(){
    String [] JudulKolom={"No","Kelas","Wali Kelas","Status","Golongan"};
    tabModel = new DefaultTableModel(null, JudulKolom){
                  boolean[] canEdit = new boolean [] { false, false, false, false };
                  @Override
                  public boolean isCellEditable(int rowIndex, int columnIndex) {
                   return canEdit [columnIndex];
                  }
              };
    TWaliKelas.setModel(tabModel);
    TWaliKelas.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
    TWaliKelas.getColumnModel().getColumn(0).setPreferredWidth(30);
    TWaliKelas.getColumnModel().getColumn(1).setPreferredWidth(100);
    TWaliKelas.getColumnModel().getColumn(2).setPreferredWidth(100);
    TWaliKelas.getColumnModel().getColumn(3).setPreferredWidth(100);
    TWaliKelas.getColumnModel().getColumn(4).setPreferredWidth(100);
    
    
    getData();
}

void ambilData_dari_JTable() {
    int row = TWaliKelas.getSelectedRow();

    String kelas = tabModel.getValueAt(row, 1).toString();
    String nama_guru = tabModel.getValueAt(row, 2).toString();
    String status_guru = tabModel.getValueAt(row, 3).toString();
    String golongan_guru = tabModel.getValueAt(row, 4).toString();
    
    CBKelas.setSelectedItem(kelas);
    txtNamaWaliKelas.setText(nama_guru);
    txtStatusWaliKelas.setText(status_guru);
    txtGolonganWaliKelas.setText(golongan_guru);
    
    }

public void hapusIsiJTable() {
    int row = tabModel.getRowCount();
    for (int i = 0; i < row; i++) {
      tabModel.removeRow(0);
    }
  }

public void tampilDataKeJTable() {
    hapusIsiJTable();
    try {
        conn.close();
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        conn=DriverManager.getConnection("jdbc:odbc:akademik_smppgri2bdg");
        String sql="Select * from wali_kelas";
        PreparedStatement st=conn.prepareStatement(sql);
        ResultSet rs=st.executeQuery();
        String kelas,nama_guru,status_guru,golongan_guru;
        int no=0;
        while(rs.next()){
         no=no+1;
         kelas=rs.getString("kelas");
         nama_guru=rs.getString("nama_guru");
         status_guru=rs.getString("status_guru");
         golongan_guru=rs.getString("golongan_guru");
         
         Object Data[]={no,kelas,nama_guru,status_guru,golongan_guru};
         tabModel.addRow(Data);
      }
  }
    catch (Exception e) {}
}

public void rubahData() {

    int ok = JOptionPane.showConfirmDialog(this,
        "Anda Yakin Ingin Mengubah Data\n Dengan kelas = '" + CBKelas.getSelectedItem() +
        "'", "Konfirmasi ",JOptionPane.YES_NO_OPTION);

    if (ok == 0) {
      try {
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        conn=DriverManager.getConnection("jdbc:odbc:akademik_smppgri2bdg");
        String sql ="UPDATE wali_kelas SET nama_guru = ?,status_guru = ?,golongan_guru = ? WHERE kelas = ?";
        PreparedStatement st = conn.prepareStatement(sql);
        try {
          st.setString(1, String.valueOf(txtNamaWaliKelas.getText()));
          st.setString(2, String.valueOf(txtStatusWaliKelas.getText()));
          st.setString(3, String.valueOf(txtGolonganWaliKelas.getText()));
          st.setString(4, String.valueOf(CBKelas.getSelectedItem()));
          st.executeUpdate();

        tampilDataKeJTable();

        CBKelas.setSelectedItem("");
        txtNamaWaliKelas.setText("");
        txtStatusWaliKelas.setText("");
        txtGolonganWaliKelas.setText("");
        } catch (SQLException se) { }
      } catch (ClassNotFoundException se) {}
      catch (SQLException se) {}
    }

  }

public void simpanData(){
   try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            conn=DriverManager.getConnection("jdbc:odbc:akademik_smppgri2bdg");
            String sql="Insert into wali_kelas values(?,?,?,?)";
            PreparedStatement st=conn.prepareStatement(sql);
                st.setString(1, String.valueOf(CBKelas.getSelectedItem()));
                st.setString(2, String.valueOf(txtNamaWaliKelas.getText()));
                st.setString(3, String.valueOf(txtStatusWaliKelas.getText()));
                st.setString(4, String.valueOf(txtGolonganWaliKelas.getText()));
            int rs=st.executeUpdate();

            if(rs>0){
            JOptionPane.showMessageDialog(this,"Input Berhasil");
      	    tampilDataKeJTable();
            }
            st.close();
            conn.close();
        }
        catch (ClassNotFoundException cnfe) {
           System.out.println("Class Driver tidak ditemukan.. : " + cnfe);
        }
        catch (SQLException sqle) {
           System.out.println("Input  Gagal = " + sqle.getMessage());
        }
        catch(Exception e){
           System.out.println("Koneksi Gagal " +e.getMessage());
        }
  }

public void hapus_Data() {
    ambilData_dari_JTable();
    int ok = JOptionPane.showConfirmDialog(this,
        "Anda Yakin Ingin Menghapus Data\nDengan kelas = '" + CBKelas.getSelectedItem() +
        "'", "Konfirmasi Menghapus Data",JOptionPane.YES_NO_OPTION);
    if (ok == 0) {
      try {
       Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
       conn=DriverManager.getConnection("jdbc:odbc:akademik_smppgri2bdg");
        String sql = "DELETE FROM wali_kelas WHERE kelas = ?";
        PreparedStatement st = conn.prepareStatement(sql);
        st.setString(1, String.valueOf(CBKelas.getSelectedItem()));
        int rs=st.executeUpdate();
        if(rs>0){
        tampilDataKeJTable();
        JOptionPane.showMessageDialog(this,"Data Sudah dihapus");
        }
        CBKelas.setSelectedItem("");
        txtNamaWaliKelas.setText("");
        txtStatusWaliKelas.setText("");
        txtGolonganWaliKelas.setText("");

      } catch (Exception se) {
         JOptionPane.showMessageDialog(this,"Gagal Hapus Data.. ");
       }
    }
  }
}
