/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FPenilaian.java
 *
 * Created on 26 May 14, 19:45:38
 */

package akademik_smppgri2bdg;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asep
 */
public class FPenilaian extends javax.swing.JFrame {
    public DefaultTableModel tabModel;
    public DefaultTableModel tabModel2;
    Connection conn;
    /** Creates new form FPenilaian */
    public FPenilaian() {
        initComponents();
        setJTable();
        setJTable2();
        config c = new config();
        txtKodeMatpel.setText(c.getKode());
        txtNamaMatpel.setText(c.getNamaPelajaran());
        txtNamaGuru.setText(c.getNama());
        persentetap();
        
        txtKodeMatpel.setEnabled(false);
        txtNamaMatpel.setEnabled(false);
        txtNamaGuru.setEnabled(false);
        CBKelas.setEnabled(false);
        NH1Guru.setEnabled(false);
        NH2Guru.setEnabled(false);
        NH3Guru.setEnabled(false);
        NUTSGuru.setEnabled(false);
        NUASGuru.setEnabled(false);
        txtNIS.setEnabled(false);
        txtNamaSiswa.setEnabled(false);
        NH1.setEnabled(false);
        NH2.setEnabled(false);
        NH3.setEnabled(false);
        NUTS.setEnabled(false);
        NUAS.setEnabled(false);
        NAKHIR.setEnabled(false);
        BHitung.setEnabled(false);
        Tahun.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TSiswa = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNamaMatpel = new javax.swing.JTextField();
        CBKelas = new javax.swing.JComboBox();
        txtNamaGuru = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        NH1Guru = new javax.swing.JTextField();
        NH3Guru = new javax.swing.JTextField();
        NUTSGuru = new javax.swing.JTextField();
        NUASGuru = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtKodeMatpel = new javax.swing.JTextField();
        NH2Guru = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtNamaSiswa = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        NH1 = new javax.swing.JTextField();
        NH2 = new javax.swing.JTextField();
        NH3 = new javax.swing.JTextField();
        NUTS = new javax.swing.JTextField();
        NUAS = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        BHitung = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        NAKHIR = new javax.swing.JTextField();
        txtNIS = new javax.swing.JTextField();
        BCariSiswa = new javax.swing.JButton();
        label1 = new java.awt.Label();
        txtNIS1 = new javax.swing.JTextField();
        BCariSiswa1 = new javax.swing.JButton();
        PanelButtonGuru = new javax.swing.JPanel();
        BTambah = new javax.swing.JButton();
        BEdit = new javax.swing.JButton();
        BSimpan = new javax.swing.JButton();
        BHapus = new javax.swing.JButton();
        BBatal = new javax.swing.JButton();
        BKeluar = new javax.swing.JButton();
        PanelPencarianGuru = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        CBCariNilai = new javax.swing.JComboBox();
        txtCariNilai = new javax.swing.JTextField();
        BCariNilai = new javax.swing.JButton();
        PanelTabelGuru = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TNilai = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        Tahun = new javax.swing.JTextField();

        jLabel30.setText("Daftar Siswa");

        TSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TSiswa);

        jButton3.setText("Pilih");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Batal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDialog1Layout.createSequentialGroup()
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialog1Layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 252, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Penilaian");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));

        jLabel3.setText("Kode Mata Pelajaran");

        jLabel4.setText("Mata Pelajaran");

        jLabel5.setText("Guru");

        jLabel6.setText("Kelas");

        txtNamaMatpel.setEnabled(false);

        CBKelas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Pilih--", "X 1", "X 2", "X 3", "X 4", "X 5" }));
        CBKelas.setEnabled(false);
        CBKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBKelasActionPerformed(evt);
            }
        });

        txtNamaGuru.setEnabled(false);

        jLabel7.setText("Persentase Penilaian :");

        jLabel8.setText("Nilai Ulangan Pertama");

        jLabel9.setText("Nilai Ulangan Kedua");

        jLabel10.setText("Nilai Ulangan Ketiga");

        jLabel11.setText("Nilai UTS");

        jLabel12.setText("Nilai UAS");

        NH1Guru.setText("0");
        NH1Guru.setEnabled(false);
        NH1Guru.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                NH1GuruCaretUpdate(evt);
            }
        });
        NH1Guru.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NH1GuruKeyTyped(evt);
            }
        });

        NH3Guru.setText("0");
        NH3Guru.setEnabled(false);
        NH3Guru.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                NH3GuruCaretUpdate(evt);
            }
        });
        NH3Guru.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NH3GuruKeyTyped(evt);
            }
        });

        NUTSGuru.setText("0");
        NUTSGuru.setEnabled(false);
        NUTSGuru.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                NUTSGuruCaretUpdate(evt);
            }
        });
        NUTSGuru.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NUTSGuruKeyTyped(evt);
            }
        });

        NUASGuru.setText("0");
        NUASGuru.setEnabled(false);
        NUASGuru.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                NUASGuruCaretUpdate(evt);
            }
        });
        NUASGuru.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NUASGuruKeyTyped(evt);
            }
        });

        jLabel13.setText("%");

        jLabel14.setText("%");

        jLabel16.setText("%");

        jLabel17.setText("%");

        jLabel18.setText("%");

        txtKodeMatpel.setEnabled(false);
        txtKodeMatpel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKodeMatpelKeyPressed(evt);
            }
        });

        NH2Guru.setText("0");
        NH2Guru.setEnabled(false);
        NH2Guru.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                NH2GuruCaretUpdate(evt);
            }
        });
        NH2Guru.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NH2GuruKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addComponent(jLabel8))
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(NUASGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel18))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(NUTSGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel17))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(NH3Guru, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel16))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(NH2Guru, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel14))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(NH1Guru, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel13))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNamaGuru)
                            .addComponent(CBKelas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNamaMatpel, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)))
                    .addComponent(txtKodeMatpel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKodeMatpel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNamaMatpel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNamaGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CBKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NH1Guru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(NH2Guru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NH3Guru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NUTSGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NUASGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel12))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));

        jLabel20.setText("Nama Siswa");

        jLabel21.setText("NIS");

        txtNamaSiswa.setEnabled(false);
        txtNamaSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaSiswaActionPerformed(evt);
            }
        });

        jLabel22.setText("Penilaian :");

        jLabel23.setText("Nilai Ulangan Pertama");

        jLabel24.setText("Nilai Ulangan Kedua");

        jLabel25.setText("Nilai Ulangan Ketiga");

        jLabel26.setText("Nilai UTS");

        jLabel27.setText("Nilai UAS");

        NH1.setEnabled(false);
        NH1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NH1KeyTyped(evt);
            }
        });

        NH2.setEnabled(false);
        NH2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NH2KeyTyped(evt);
            }
        });

        NH3.setEnabled(false);
        NH3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NH3KeyTyped(evt);
            }
        });

        NUTS.setEnabled(false);
        NUTS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NUTSKeyTyped(evt);
            }
        });

        NUAS.setEnabled(false);
        NUAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUASActionPerformed(evt);
            }
        });
        NUAS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NUASKeyTyped(evt);
            }
        });

        jLabel15.setText("INPUT NILAI SISWA :");

        BHitung.setText("Hitung Nilai Akhir");
        BHitung.setEnabled(false);
        BHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHitungActionPerformed(evt);
            }
        });

        jLabel28.setText("Nilai Akhir");

        NAKHIR.setEnabled(false);

        txtNIS.setEnabled(false);
        txtNIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNISActionPerformed(evt);
            }
        });
        txtNIS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNISKeyPressed(evt);
            }
        });

        BCariSiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/search.png"))); // NOI18N
        BCariSiswa.setText("Cari");
        BCariSiswa.setEnabled(false);
        BCariSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCariSiswaActionPerformed(evt);
            }
        });

        label1.setText("Kelas");

        txtNIS1.setEnabled(false);
        txtNIS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNIS1ActionPerformed(evt);
            }
        });
        txtNIS1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNIS1KeyPressed(evt);
            }
        });

        BCariSiswa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/search.png"))); // NOI18N
        BCariSiswa1.setText("Cari");
        BCariSiswa1.setEnabled(false);
        BCariSiswa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCariSiswa1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtNIS, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BCariSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtNIS1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BCariSiswa1, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(13, 13, 13)
                                .addComponent(txtNamaSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel27)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                                        .addComponent(NUAS, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                        .addComponent(NH2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(NH1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                        .addComponent(NH3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NUTS, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel28)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                        .addComponent(NAKHIR, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(BHitung, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BCariSiswa1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNIS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BCariSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addComponent(txtNamaSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(NH1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(NH2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(NH3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel27))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(NUTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NUAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BHitung)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(NAKHIR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
        );

        PanelButtonGuru.setBackground(new java.awt.Color(204, 204, 255));
        PanelButtonGuru.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelButtonGuru.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/add.png"))); // NOI18N
        BTambah.setText("Tambah");
        BTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTambahActionPerformed(evt);
            }
        });
        PanelButtonGuru.add(BTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 110, -1));

        BEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/edit.png"))); // NOI18N
        BEdit.setText("Edit");
        BEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEditActionPerformed(evt);
            }
        });
        PanelButtonGuru.add(BEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 110, -1));

        BSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/save.png"))); // NOI18N
        BSimpan.setText("Simpan");
        BSimpan.setEnabled(false);
        BSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSimpanActionPerformed(evt);
            }
        });
        PanelButtonGuru.add(BSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 110, -1));

        BHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/delete.png"))); // NOI18N
        BHapus.setText("Hapus");
        BHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHapusActionPerformed(evt);
            }
        });
        PanelButtonGuru.add(BHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 110, -1));

        BBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/cancel.png"))); // NOI18N
        BBatal.setText("Batal");
        BBatal.setEnabled(false);
        BBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBatalActionPerformed(evt);
            }
        });
        PanelButtonGuru.add(BBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 110, -1));

        BKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/close.png"))); // NOI18N
        BKeluar.setText("Keluar");
        BKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BKeluarActionPerformed(evt);
            }
        });
        PanelButtonGuru.add(BKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 110, -1));

        PanelPencarianGuru.setBackground(new java.awt.Color(204, 204, 255));
        PanelPencarianGuru.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel29.setText("Cari Berdasarkan");

        CBCariNilai.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NIP", "Nama Siswa" }));

        txtCariNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariNilaiActionPerformed(evt);
            }
        });

        BCariNilai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/search.png"))); // NOI18N
        BCariNilai.setText("Cari");
        BCariNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCariNilaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPencarianGuruLayout = new javax.swing.GroupLayout(PanelPencarianGuru);
        PanelPencarianGuru.setLayout(PanelPencarianGuruLayout);
        PanelPencarianGuruLayout.setHorizontalGroup(
            PanelPencarianGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPencarianGuruLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBCariNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCariNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BCariNilai, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelPencarianGuruLayout.setVerticalGroup(
            PanelPencarianGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPencarianGuruLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelPencarianGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(CBCariNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCariNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BCariNilai))
                .addContainerGap())
        );

        PanelTabelGuru.setBackground(new java.awt.Color(204, 204, 255));
        PanelTabelGuru.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "DATA TABEL NILAI", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        TNilai.setBackground(new java.awt.Color(255, 255, 204));
        TNilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TNilai);

        javax.swing.GroupLayout PanelTabelGuruLayout = new javax.swing.GroupLayout(PanelTabelGuru);
        PanelTabelGuru.setLayout(PanelTabelGuruLayout);
        PanelTabelGuruLayout.setHorizontalGroup(
            PanelTabelGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTabelGuruLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelTabelGuruLayout.setVerticalGroup(
            PanelTabelGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTabelGuruLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel19.setText("TAHUN AJARAN");

        Tahun.setText("2012 - 2013");
        Tahun.setEnabled(false);
        Tahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TahunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelButtonGuru, javax.swing.GroupLayout.DEFAULT_SIZE, 1012, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Tahun, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(PanelPencarianGuru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(PanelTabelGuru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelButtonGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(Tahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelTabelGuru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelPencarianGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBKelasActionPerformed

    private void BHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHitungActionPerformed
        // TODO add your handling code here:
        persentase2(NH1Guru.getText(),NH2Guru.getText(),NH3Guru.getText(),NUTSGuru.getText(),NUASGuru.getText());

    }//GEN-LAST:event_BHitungActionPerformed

    private void BTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTambahActionPerformed
        // TODO add your handling code here:
        if (NH1Guru.getText().equals("0"))
        {
            txtNIS.setText("");
            txtNamaSiswa.setText("");
            NH1.setText("");
            NH2.setText("");
            NH3.setText("");
            NUTS.setText("");
            NUAS.setText("");
            NAKHIR.setText("");

            txtKodeMatpel.setEnabled(false);
            txtNamaMatpel.setEnabled(false);
            txtNamaGuru.setEnabled(false);
            CBKelas.setEnabled(true);
            NH1Guru.setEnabled(true);
            NH2Guru.setEnabled(true);
            NH3Guru.setEnabled(true);
            NUTSGuru.setEnabled(true);
            NUASGuru.setEnabled(true);
            txtNIS.setEnabled(false);
            txtNamaSiswa.setEnabled(false);
            NH1.setEnabled(true);
            NH2.setEnabled(true);
            NH3.setEnabled(true);
            NUTS.setEnabled(true);
            NUAS.setEnabled(true);
            NAKHIR.setEnabled(false);
            BHitung.setEnabled(true);
            Tahun.setEnabled(false);

            BSimpan.setText("Simpan");
        
            BCariSiswa.setEnabled(true);
            BTambah.setEnabled(false);
            BSimpan.setEnabled(true);
            BEdit.setEnabled(false);
            BBatal.setEnabled(true);
            BHapus.setEnabled(false);
            BKeluar.setEnabled(false);
        }
        else
        {
            txtNIS.setText("");
            txtNamaSiswa.setText("");
            NH1.setText("");
            NH2.setText("");
            NH3.setText("");
            NUTS.setText("");
            NUAS.setText("");
            NAKHIR.setText("");


            txtKodeMatpel.setEnabled(false);
            txtNamaMatpel.setEnabled(false);
            txtNamaGuru.setEnabled(false);
            CBKelas.setEnabled(true);
            NH1Guru.setEnabled(false);
            NH2Guru.setEnabled(false);
            NH3Guru.setEnabled(false);
            NUTSGuru.setEnabled(false);
            NUASGuru.setEnabled(false);
            txtNIS.setEnabled(false);
            txtNamaSiswa.setEnabled(false);
            NH1.setEnabled(true);
            NH2.setEnabled(true);
            NH3.setEnabled(true);
            NUTS.setEnabled(true);
            NUAS.setEnabled(true);
            NAKHIR.setEnabled(false);
            BHitung.setEnabled(true);
            Tahun.setEnabled(false);

            BSimpan.setText("Simpan");

            BCariSiswa.setEnabled(true);
            BTambah.setEnabled(false);
            BSimpan.setEnabled(true);
            BEdit.setEnabled(false);
            BBatal.setEnabled(true);
            BHapus.setEnabled(false);
            BKeluar.setEnabled(false);
        }

}//GEN-LAST:event_BTambahActionPerformed

    private void BEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEditActionPerformed
        // TODO add your handling code here:
        CBKelas.setSelectedItem("--Pilih--");
        txtNIS.setText("");
        txtNamaSiswa.setText("");
        NH1.setText("");
        NH2.setText("");
        NH3.setText("");
        NUTS.setText("");
        NUAS.setText("");
        NAKHIR.setText("");

        txtKodeMatpel.setEnabled(false);
        txtNamaMatpel.setEnabled(false);
        txtNamaGuru.setEnabled(false);
        CBKelas.setEnabled(true);
        NH1Guru.setEnabled(false);
        NH2Guru.setEnabled(false);
        NH3Guru.setEnabled(false);
        NUTSGuru.setEnabled(false);
        NUASGuru.setEnabled(false);
        txtNIS.setEnabled(false);
        txtNamaSiswa.setEnabled(false);
        NH1.setEnabled(true);
        NH2.setEnabled(true);
        NH3.setEnabled(true);
        NUTS.setEnabled(true);
        NUAS.setEnabled(true);
        NAKHIR.setEnabled(false);
        BHitung.setEnabled(true);
        Tahun.setEnabled(false);

        BSimpan.setText("Update");

        BCariSiswa.setEnabled(true);
        BTambah.setEnabled(false);
        BSimpan.setEnabled(true);
        BEdit.setEnabled(false);
        BBatal.setEnabled(true);
        BHapus.setEnabled(false);
        BKeluar.setEnabled(false);

        ambilData_dari_JTable();
}//GEN-LAST:event_BEditActionPerformed

    private void BSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSimpanActionPerformed
        // TODO add your handling code here:
        if(txtKodeMatpel.getText().isEmpty() ||
           txtNamaMatpel.getText().isEmpty() ||
           txtNamaGuru.getText().isEmpty() ||
           CBKelas.getSelectedItem().equals("--Pilih--") ||
           NH1Guru.getText().isEmpty() ||
           NH2Guru.getText().isEmpty() ||
           NH3Guru.getText().isEmpty() ||
           NUTSGuru.getText().isEmpty() ||
           NUASGuru.getText().isEmpty() ||
           txtNIS.getText().isEmpty() ||
           txtNamaSiswa.getText().isEmpty() ||
           NH1.getText().isEmpty() ||
           NH1.getText().isEmpty() ||
           NH1.getText().isEmpty() ||
           NUTS.getText().isEmpty() ||
           NUAS.getText().isEmpty() ||
           NAKHIR.getText().isEmpty() ||
           Tahun.getText().isEmpty() )
           {
            JOptionPane.showMessageDialog(this,"Data Tidak Lengkap!!");

           } else
             if(BSimpan.getText().equalsIgnoreCase("Simpan"))
                simpanData();
             else
                rubahData();
                
        txtKodeMatpel.setEnabled(false);
        txtNamaMatpel.setEnabled(false);
        txtNamaGuru.setEnabled(false);
        CBKelas.setEnabled(true);
        NH1Guru.setEnabled(true);
        NH2Guru.setEnabled(true);
        NH3Guru.setEnabled(true);
        NUTSGuru.setEnabled(true);
        NUASGuru.setEnabled(true);
        txtNIS.setEnabled(true);
        txtNamaSiswa.setEnabled(true);
        NH1.setEnabled(true);
        NH2.setEnabled(true);
        NH3.setEnabled(true);
        NUTS.setEnabled(true);
        NUAS.setEnabled(true);
        NAKHIR.setEnabled(false);
        BHitung.setEnabled(true);
        Tahun.setEnabled(false);

        txtKodeMatpel.setEnabled(false);
        txtNamaMatpel.setEnabled(false);
        txtNamaGuru.setEnabled(false);
        CBKelas.setEnabled(false);
        NH1Guru.setEnabled(false);
        NH2Guru.setEnabled(false);
        NH3Guru.setEnabled(false);
        NUTSGuru.setEnabled(false);
        NUASGuru.setEnabled(false);
        txtNIS.setEnabled(false);
        txtNamaSiswa.setEnabled(false);
        NH1.setEnabled(false);
        NH2.setEnabled(false);
        NH3.setEnabled(false);
        NUTS.setEnabled(false);
        NUAS.setEnabled(false);
        NAKHIR.setEnabled(false);
        BHitung.setEnabled(false);
        Tahun.setEnabled(false);

        BCariSiswa.setEnabled(false);
        BTambah.setEnabled(true);
        BSimpan.setEnabled(false);
        BEdit.setEnabled(true);
        BBatal.setEnabled(false);
        BHapus.setEnabled(true);
        BKeluar.setEnabled(true);
}//GEN-LAST:event_BSimpanActionPerformed

    private void BHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHapusActionPerformed
        // TODO add your handling code here:
        hapus_Data();
}//GEN-LAST:event_BHapusActionPerformed

    private void BBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBatalActionPerformed
        // TODO add your handling code here:
        if (NH1Guru.getText().equals("0")){
        CBKelas.setSelectedItem("--Pilih--");
        
        txtKodeMatpel.setEnabled(false);
        txtNamaMatpel.setEnabled(false);
        txtNamaGuru.setEnabled(false);
        CBKelas.setEnabled(false);
        NH1Guru.setEnabled(false);
        NH2Guru.setEnabled(false);
        NH3Guru.setEnabled(false);
        NUTSGuru.setEnabled(false);
        NUASGuru.setEnabled(false);
        txtNIS.setEnabled(false);
        txtNamaSiswa.setEnabled(false);
        NH1.setEnabled(false);
        NH2.setEnabled(false);
        NH3.setEnabled(false);
        NUTS.setEnabled(false);
        NUAS.setEnabled(false);
        NAKHIR.setEnabled(false);
        BHitung.setEnabled(false);
        Tahun.setEnabled(false);

        BCariSiswa.setEnabled(false);
        BTambah.setEnabled(true);
        BSimpan.setEnabled(false);
        BEdit.setEnabled(true);
        BBatal.setEnabled(false);
        BHapus.setEnabled(true);
        BKeluar.setEnabled(true);
        }
        else{
        CBKelas.setSelectedItem("--Pilih--");
        
        txtKodeMatpel.setEnabled(false);
        txtNamaMatpel.setEnabled(false);
        txtNamaGuru.setEnabled(false);
        CBKelas.setEnabled(false);
        NH1Guru.setEnabled(false);
        NH2Guru.setEnabled(false);
        NH3Guru.setEnabled(false);
        NUTSGuru.setEnabled(false);
        NUASGuru.setEnabled(false);
        txtNIS.setEnabled(false);
        txtNamaSiswa.setEnabled(false);
        NH1.setEnabled(false);
        NH2.setEnabled(false);
        NH3.setEnabled(false);
        NUTS.setEnabled(false);
        NUAS.setEnabled(false);
        NAKHIR.setEnabled(false);
        BHitung.setEnabled(false);
        Tahun.setEnabled(false);

        BCariSiswa.setEnabled(false);
        BTambah.setEnabled(true);
        BSimpan.setEnabled(false);
        BEdit.setEnabled(true);
        BBatal.setEnabled(false);
        BHapus.setEnabled(true);
        BKeluar.setEnabled(true);
        }
}//GEN-LAST:event_BBatalActionPerformed

    private void BKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BKeluarActionPerformed
        // TODO add your handling code here:
        dispose();
}//GEN-LAST:event_BKeluarActionPerformed

    private void BCariNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCariNilaiActionPerformed
        // TODO add your handling code here:
        String sql;
        int pilih = CBCariNilai.getSelectedIndex();
        String cari = txtCariNilai.getText();
        try {
            conn.close();
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            conn=DriverManager.getConnection("jdbc:odbc:akademik_smppgri2bdg");
            if(pilih==0)
                sql ="Select * from nilai WHERE nip ='" +txtCariNilai.getText() + "'";
            else
                sql ="Select * from nilai WHERE nama_siswa Like '%" +txtCariNilai.getText() + "%'";

            PreparedStatement st = conn.prepareStatement(sql);
            ResultSet rs =st.executeQuery();

            hapusIsiJTable();
            int no=0;
            while (rs.next()) {
                no++;
                String kode_mata_pelajaran = rs.getString("kode_mata_pelajaran");
                String nama_mata_pelajaran = rs.getString("nama_mata_pelajaran");
                String nama_guru = rs.getString("nama_guru");
                String nama_kelas = rs.getString("nama_kelas");
                String persentase_nh1 = rs.getString("persentase_nh1");
                String persentase_nh2 = rs.getString("persentase_nh2");
                String persentase_nh3 = rs.getString("persentase_nh3");
                String persentase_nuts = rs.getString("persentase_nuts");
                String persentase_nuas = rs.getString("persentase_nuas");
                String nis = rs.getString("nis");
                String nama_siswa = rs.getString("nama_siswa");
                String nh1 = rs.getString("nh1");
                String nh2 = rs.getString("nh2");
                String nh3 = rs.getString("nh3");
                String nuts = rs.getString("nuts");
                String nuas = rs.getString("nuas");
                String nakhir = rs.getString("nakhir");
                String tahun_ajaran = rs.getString("tahun_ajaran");

                Object [] data = {no,kode_mata_pelajaran,nama_mata_pelajaran,nama_guru,nama_kelas,
                                  persentase_nh1,persentase_nh2,persentase_nh3,persentase_nuts,persentase_nuas,
                                  nis,nama_siswa,nh1,nh2,nh3,
                                  nuts,nuas,nakhir,tahun_ajaran };
                tabModel.addRow(data);
            }

            if(tabModel.getRowCount()>0)
                JOptionPane.showMessageDialog(this,"Data Ditemukan ");
            else
                JOptionPane.showMessageDialog(this,"Data Tidak Ditemukan.. ");

        } catch (ClassNotFoundException se) {}
        catch (SQLException se) {}
}//GEN-LAST:event_BCariNilaiActionPerformed

    private void txtKodeMatpelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKodeMatpelKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
        try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            conn=DriverManager.getConnection("jdbc:odbc:akademik_smppgri2bdg");
            String sql="select * from user where kode_mata_pelajaran= ?";
            PreparedStatement st=conn.prepareStatement(sql);
            st.setString(1, txtKodeMatpel.getText());
            ResultSet rs=st.executeQuery();
            while(rs.next()){
                txtNamaMatpel.setText(rs.getString("nama_mata_pelajaran"));
                txtNamaGuru.setText(rs.getString("nama_guru"));


            }
            
            st.close();
            conn.close();

        } catch (ClassNotFoundException cnfe) {  
            System.out.println("Class Driver tidak ditemukan.. : " + cnfe);
            System.exit(0);
        } catch (SQLException sqle) {   
            System.out.println("Proses Query Gagal = " + sqle);
            System.exit(0);
        } catch(Exception e){
            System.out.println("Koneksi Access Gagal " +e.getMessage());
            System.exit(0);
        }
        }
    }//GEN-LAST:event_txtKodeMatpelKeyPressed

    private void txtNISKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNISKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
        try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            conn=DriverManager.getConnection("jdbc:odbc:akademik_smppgri2bdg");
            String sql="select * from siswa where nis='"+txtNIS.getText()+"'";
            PreparedStatement st=conn.prepareStatement(sql);
            ResultSet rs=st.executeQuery();
            int no=0+1;
            while(rs.next()){
                txtNamaSiswa.setText(rs.getString("nama_siswa"));
            }

            st.close();
            conn.close();

        } catch (ClassNotFoundException cnfe) {
            System.out.println("Class Driver tidak ditemukan.. : " + cnfe);
            System.exit(0);
        } catch (SQLException sqle) {
            System.out.println("Proses Query Gagal = " + sqle);
            System.exit(0);
        } catch(Exception e){
            System.out.println("Koneksi Access Gagal " +e.getMessage());
            System.exit(0);
        }
        }
    }//GEN-LAST:event_txtNISKeyPressed

    private void NH1GuruKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NH1GuruKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') && NH1Guru.getText().length() < 15
            || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
       
    }//GEN-LAST:event_NH1GuruKeyTyped

    private void NH2GuruKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NH2GuruKeyTyped
        // TODO add your handling code here:
                char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') && NH2Guru.getText().length() < 15
            || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
                
    }//GEN-LAST:event_NH2GuruKeyTyped

    private void NH3GuruKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NH3GuruKeyTyped
        // TODO add your handling code here:
                char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') && NH3Guru.getText().length() < 15
            || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
                
    }//GEN-LAST:event_NH3GuruKeyTyped

    private void NUTSGuruKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NUTSGuruKeyTyped
        // TODO add your handling code here:
                 char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') && NUTSGuru.getText().length() < 15
            || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
                 
    }//GEN-LAST:event_NUTSGuruKeyTyped

    private void NUASGuruKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NUASGuruKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') && NUASGuru.getText().length() < 15
            || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
        
    }//GEN-LAST:event_NUASGuruKeyTyped

    private void NH1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NH1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') && NH1.getText().length() < 15
            || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_NH1KeyTyped

    private void NH2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NH2KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') && NH2.getText().length() < 15
            || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_NH2KeyTyped

    private void NH3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NH3KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') && NH3.getText().length() < 15
            || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_NH3KeyTyped

    private void NUTSKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NUTSKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') && NUTS.getText().length() < 15
            || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_NUTSKeyTyped

    private void NUASKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NUASKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') && NUAS.getText().length() < 15
            || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_NUASKeyTyped

    private void NH1GuruCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_NH1GuruCaretUpdate
        // TODO add your handling code here:
        try {
            persentase(NH1Guru.getText(), NH2Guru.getText(), NH3Guru.getText(), NUTSGuru.getText(), NUASGuru.getText());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_NH1GuruCaretUpdate

    private void NH2GuruCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_NH2GuruCaretUpdate
        // TODO add your handling code here:
        try {
            persentase(NH1Guru.getText(), NH2Guru.getText(), NH3Guru.getText(), NUTSGuru.getText(), NUASGuru.getText());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_NH2GuruCaretUpdate

    private void NH3GuruCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_NH3GuruCaretUpdate
        // TODO add your handling code here:
        try {
            persentase(NH1Guru.getText(), NH2Guru.getText(), NH3Guru.getText(), NUTSGuru.getText(), NUASGuru.getText());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_NH3GuruCaretUpdate

    private void NUTSGuruCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_NUTSGuruCaretUpdate
        // TODO add your handling code here:
        try {
            persentase(NH1Guru.getText(), NH2Guru.getText(), NH3Guru.getText(), NUTSGuru.getText(), NUASGuru.getText());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_NUTSGuruCaretUpdate

    private void NUASGuruCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_NUASGuruCaretUpdate
        // TODO add your handling code here:
        try {
            persentase(NH1Guru.getText(), NH2Guru.getText(), NH3Guru.getText(), NUTSGuru.getText(), NUASGuru.getText());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_NUASGuruCaretUpdate

    private void txtNamaSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaSiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaSiswaActionPerformed

    private void TahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TahunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TahunActionPerformed

    private void BCariSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCariSiswaActionPerformed
        // TODO add your handling code here:
        jDialog1.setSize(343, 300);
        jDialog1.setModal(true);
        jDialog1.setLocationRelativeTo(this);
        jDialog1.setVisible(true);
    }//GEN-LAST:event_BCariSiswaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(TSiswa.getSelectedRow()==-1) {
            JOptionPane.showMessageDialog(this, "Silahkan Pilih Data Terlebih Dahulu");
        } else {
            int row=TSiswa.getSelectedRow();
            txtNIS.setText(TSiswa.getValueAt(row, 1).toString());
            txtNamaSiswa.setText(TSiswa.getValueAt(row, 2).toString());
            jDialog1.dispose();
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jDialog1.dispose();
}//GEN-LAST:event_jButton2ActionPerformed

    private void txtNISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNISActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNISActionPerformed

    private void txtNIS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNIS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNIS1ActionPerformed

    private void txtNIS1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNIS1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNIS1KeyPressed

    private void BCariSiswa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCariSiswa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BCariSiswa1ActionPerformed

    private void NUASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NUASActionPerformed

    private void txtCariNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariNilaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariNilaiActionPerformed
    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new FPenilaian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBatal;
    private javax.swing.JButton BCariNilai;
    private javax.swing.JButton BCariSiswa;
    private javax.swing.JButton BCariSiswa1;
    private javax.swing.JButton BEdit;
    private javax.swing.JButton BHapus;
    private javax.swing.JButton BHitung;
    private javax.swing.JButton BKeluar;
    private javax.swing.JButton BSimpan;
    private javax.swing.JButton BTambah;
    private javax.swing.JComboBox CBCariNilai;
    private javax.swing.JComboBox CBKelas;
    private javax.swing.JTextField NAKHIR;
    private javax.swing.JTextField NH1;
    private javax.swing.JTextField NH1Guru;
    private javax.swing.JTextField NH2;
    private javax.swing.JTextField NH2Guru;
    private javax.swing.JTextField NH3;
    private javax.swing.JTextField NH3Guru;
    private javax.swing.JTextField NUAS;
    private javax.swing.JTextField NUASGuru;
    private javax.swing.JTextField NUTS;
    private javax.swing.JTextField NUTSGuru;
    private javax.swing.JPanel PanelButtonGuru;
    private javax.swing.JPanel PanelPencarianGuru;
    private javax.swing.JPanel PanelTabelGuru;
    private javax.swing.JTable TNilai;
    private javax.swing.JTable TSiswa;
    private javax.swing.JTextField Tahun;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label label1;
    private javax.swing.JTextField txtCariNilai;
    private javax.swing.JTextField txtKodeMatpel;
    private javax.swing.JTextField txtNIS;
    private javax.swing.JTextField txtNIS1;
    private javax.swing.JTextField txtNamaGuru;
    private javax.swing.JTextField txtNamaMatpel;
    private javax.swing.JTextField txtNamaSiswa;
    // End of variables declaration//GEN-END:variables

     private void getData(){

  try{
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");

        conn=DriverManager.getConnection("jdbc:odbc:akademik_smppgri2bdg");

        String sql="Select * from nilai";
        PreparedStatement st=conn.prepareStatement(sql);

        ResultSet rs=st.executeQuery();

        String kode_mata_pelajaran,nama_mata_pelajaran,nama_guru,nama_kelas,
               persentase_nh1,persentase_nh2,persentase_nh3,persentase_nuts,persentase_nuas,
               nis,nama_siswa,nh1,nh2,nh3,
               nuts,nuas,nakhir,tahun_ajaran;
        int no=0;
        while(rs.next()){
         no=no+1;
         kode_mata_pelajaran = rs.getString("kode_mata_pelajaran");
         nama_mata_pelajaran = rs.getString("nama_mata_pelajaran");
         nama_guru = rs.getString("nama_guru");
         nama_kelas = rs.getString("nama_kelas");
         persentase_nh1 = rs.getString("persentase_nh1");
         persentase_nh2 = rs.getString("persentase_nh2");
         persentase_nh3 = rs.getString("persentase_nh3");
         persentase_nuts = rs.getString("persentase_nuts");
         persentase_nuas = rs.getString("persentase_nuas");
         nis = rs.getString("nis");
         nama_siswa = rs.getString("nama_siswa");
         nh1 = rs.getString("nh1");
         nh2 = rs.getString("nh2");
         nh3 = rs.getString("nh3");
         nuts = rs.getString("nuts");
         nuas = rs.getString("nuas");
         nakhir = rs.getString("nakhir");
         tahun_ajaran = rs.getString("tahun_ajaran");
         Object [] Data = {no,kode_mata_pelajaran,nama_mata_pelajaran,nama_guru,nama_kelas,
                           persentase_nh1,persentase_nh2,persentase_nh3,persentase_nuts,persentase_nuas,
                           nis,nama_siswa,nh1,nh2,nh3,
                           nuts,nuas,nakhir,tahun_ajaran };
         tabModel.addRow(Data);
        }

          st.close();
          conn.close();
    }
    catch (ClassNotFoundException cnfe) {
           System.out.println("Class Driver tidak ditemukan.. : " + cnfe);
           System.exit(0);
    }
    catch (SQLException sqle) {
           System.out.println("Proses Query Gagal = " + sqle);
           System.exit(0);
    }
    catch(Exception e){
           System.out.println("Koneksi Access Gagal " +e.getMessage());
           System.exit(0);
    }

    }

private void setJTable(){
    String [] JudulKolom={"No","Kode Matpel","Nama Matpel","Nama Guru","Nama Kelas",
                          "Persentase nh1","Persentase nh2","Persentase_nh3","Persentase nuts","Persentase nuas",
                          "NIS","Nama Siswa","Nilai Harian 1","Nilai Harian 2","Nilai Harian 3",
                          "Nilai UTS","Nilai UAS","Nilai Akhir","Tahun AJaran" };
    tabModel = new DefaultTableModel(null, JudulKolom){
                  boolean[] canEdit = new boolean [] { false, false, false, false, false,
                                                       false, false, false, false, false,
                                                       false, false, false, false, false,
                                                       false, false, false, false };
                  @Override
                  public boolean isCellEditable(int rowIndex, int columnIndex) {
                   return canEdit [columnIndex];
                  }
              };
    TNilai.setModel(tabModel);
    TNilai.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
    TNilai.getColumnModel().getColumn(0).setPreferredWidth(30);
    TNilai.getColumnModel().getColumn(1).setPreferredWidth(100);
    TNilai.getColumnModel().getColumn(2).setPreferredWidth(100);
    TNilai.getColumnModel().getColumn(3).setPreferredWidth(100);
    TNilai.getColumnModel().getColumn(4).setPreferredWidth(100);
    TNilai.getColumnModel().getColumn(5).setPreferredWidth(100);
    TNilai.getColumnModel().getColumn(6).setPreferredWidth(100);
    TNilai.getColumnModel().getColumn(7).setPreferredWidth(100);
    TNilai.getColumnModel().getColumn(8).setPreferredWidth(100);
    TNilai.getColumnModel().getColumn(9).setPreferredWidth(100);
    TNilai.getColumnModel().getColumn(10).setPreferredWidth(100);
    TNilai.getColumnModel().getColumn(11).setPreferredWidth(100);
    TNilai.getColumnModel().getColumn(12).setPreferredWidth(100);
    TNilai.getColumnModel().getColumn(13).setPreferredWidth(100);
    TNilai.getColumnModel().getColumn(14).setPreferredWidth(100);
    TNilai.getColumnModel().getColumn(15).setPreferredWidth(100);
    TNilai.getColumnModel().getColumn(16).setPreferredWidth(100);
    TNilai.getColumnModel().getColumn(17).setPreferredWidth(100);
    TNilai.getColumnModel().getColumn(18).setPreferredWidth(100);
    getData();
}

void ambilData_dari_JTable() {
    int row = TNilai.getSelectedRow();

    String kode_mata_pelajaran = tabModel.getValueAt(row, 1).toString();
    String nama_mata_pelajaran = tabModel.getValueAt(row, 2).toString();
    String nama_guru = tabModel.getValueAt(row, 3).toString();
    String nama_kelas = tabModel.getValueAt(row, 4).toString();
    String persentase_nh1 = tabModel.getValueAt(row, 5).toString();
    String persentase_nh2 = tabModel.getValueAt(row, 6).toString();
    String persentase_nh3 = tabModel.getValueAt(row, 7).toString();
    String persentase_nuts = tabModel.getValueAt(row, 8).toString();
    String persentase_nuas = tabModel.getValueAt(row, 9).toString();
    String nis = tabModel.getValueAt(row, 10).toString();
    String nama_siswa = tabModel.getValueAt(row, 11).toString();
    String nh1 = tabModel.getValueAt(row, 12).toString();
    String nh2 = tabModel.getValueAt(row, 13).toString();
    String nh3 = tabModel.getValueAt(row, 14).toString();
    String nuts = tabModel.getValueAt(row, 15).toString();
    String nuas = tabModel.getValueAt(row, 16).toString();
    String nakhir = tabModel.getValueAt(row, 17).toString();
    String tahun_ajaran = tabModel.getValueAt(row, 18).toString();

    txtKodeMatpel.setText(kode_mata_pelajaran);
    txtNamaMatpel.setText(nama_mata_pelajaran);
    txtNamaGuru.setText(nama_guru);
    CBKelas.setSelectedItem(nama_kelas);
    NH1Guru.setText(persentase_nh1);
    NH2Guru.setText(persentase_nh2);
    NH3Guru.setText(persentase_nh3);
    NUTSGuru.setText(persentase_nuts);
    NUASGuru.setText(persentase_nuas);
    txtNIS.setText(nis);
    txtNamaSiswa.setText(nama_siswa);
    NH1.setText(nh1);
    NH2.setText(nh2);
    NH3.setText(nh3);
    NUTS.setText(nuts);
    NUAS.setText(nuas);
    NAKHIR.setText(nakhir);
    Tahun.setText(tahun_ajaran);

    }

public void hapusIsiJTable() {
    int row = tabModel.getRowCount();
    for (int i = 0; i < row; i++) {
      tabModel.removeRow(0);
    }
  }

public void tampilDataKeJTable() {
    hapusIsiJTable();
    try {
        conn.close();
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        conn=DriverManager.getConnection("jdbc:odbc:akademik_smppgri2bdg");
        String sql="Select * from nilai";
        PreparedStatement st=conn.prepareStatement(sql);
        ResultSet rs=st.executeQuery();
        String kode_mata_pelajaran,nama_mata_pelajaran,nama_guru,nama_kelas,
               persentase_nh1,persentase_nh2,persentase_nh3,persentase_nuts,persentase_nuas,
               nis,nama_siswa,nh1,nh2,nh3,
               nuts,nuas,nakhir,tahun_ajaran;
        int no=0;
        while(rs.next()){
         no=no+1;
         kode_mata_pelajaran = rs.getString("kode_mata_pelajaran");
         nama_mata_pelajaran = rs.getString("nama_mata_pelajaran");
         nama_guru = rs.getString("nama_guru");
         nama_kelas = rs.getString("nama_kelas");
         persentase_nh1 = rs.getString("persentase_nh1");
         persentase_nh2 = rs.getString("persentase_nh2");
         persentase_nh3 = rs.getString("persentase_nh3");
         persentase_nuts = rs.getString("persentase_nuts");
         persentase_nuas = rs.getString("persentase_nuas");
         nis = rs.getString("nis");
         nama_siswa = rs.getString("nama_siswa");
         nh1 = rs.getString("nh1");
         nh2 = rs.getString("nh2");
         nh3 = rs.getString("nh3");
         nuts = rs.getString("nuts");
         nuas = rs.getString("nuas");
         nakhir = rs.getString("nakhir");
         tahun_ajaran = rs.getString("tahun_ajaran");

         Object Data[]={no,kode_mata_pelajaran,nama_mata_pelajaran,nama_guru,nama_kelas,
                        persentase_nh1,persentase_nh2,persentase_nh3,persentase_nuts,persentase_nuas,
                        nis,nama_siswa,nh1,nh2,nh3,
                        nuts,nuas,nakhir,tahun_ajaran};
         tabModel.addRow(Data);
      }
  }
    catch (Exception e) {}
}

public void rubahData() {

    int ok = JOptionPane.showConfirmDialog(this,
        "Anda Yakin Ingin Mengubah Data\n Dengan NIP = '" + txtNIS.getText() +
        "'", "Konfirmasi ",JOptionPane.YES_NO_OPTION);

    if (ok == 0) {
      try {
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        conn=DriverManager.getConnection("jdbc:odbc:akademik_smppgri2bdg");
        String sql ="UPDATE nilai SET kode_mata_pelajaran = ?,nama_mata_pelajaran = ?,nama_guru = ?,nama_kelas = ?,persentase_nh1 = ?,persentase_nh2 = ?,persentase_nh3 = ?,persentase_nuts = ?,persentase_nuas = ?,nama_siswa = ?,nh1 = ?,nh2 = ?,nh3 = ?,nuts = ?,nuas = ?,nakhir = ?, tahun_ajaran = ? WHERE nis = ?";
        PreparedStatement st = conn.prepareStatement(sql);
        try {
          st.setString(1, txtKodeMatpel.getText());
          st.setString(2, txtNamaMatpel.getText());
          st.setString(3, txtNamaGuru.getText());
          st.setString(4, String.valueOf(CBKelas.getSelectedItem()));
          st.setString(5, NH1Guru.getText());
          st.setString(6, NH2Guru.getText());
          st.setString(7, NH3Guru.getText());
          st.setString(8, NUTSGuru.getText());
          st.setString(9, NUASGuru.getText());
          st.setString(10, txtNamaSiswa.getText());
          st.setString(11, NH1.getText());
          st.setString(12, NH2.getText());
          st.setString(13, NH3.getText());
          st.setString(14, NUTS.getText());
          st.setString(15, NUAS.getText());
          st.setString(16, NAKHIR.getText());
          st.setString(17, txtNIS.getText());
          st.setString(18, Tahun.getText());
          st.executeUpdate();
          
        tampilDataKeJTable();

        txtKodeMatpel.setText("");
        txtNamaMatpel.setText("");
        txtNamaGuru.setText("");
        CBKelas.setSelectedItem("");
        NH1Guru.setText("");
        NH2Guru.setText("");
        NH3Guru.setText("");
        NUTSGuru.setText("");
        NUASGuru.setText("");
        txtNIS.setText("");
        txtNamaSiswa.setText("");
        NH1.setText("");
        NH2.setText("");
        NH3.setText("");
        NUTS.setText("");
        NUAS.setText("");
        NAKHIR.setText("");
        } catch (SQLException se) { }
      } catch (ClassNotFoundException se) {}
      catch (SQLException se) {}
    }

  }

public void simpanData(){
    
     try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            conn=DriverManager.getConnection("jdbc:odbc:akademik_smppgri2bdg");
            String sql="Insert into nilai values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement st=conn.prepareStatement(sql);
                st.setString(1, txtKodeMatpel.getText());
                st.setString(2, txtNamaMatpel.getText());
                st.setString(3, txtNamaGuru.getText());
                st.setString(4, String.valueOf(CBKelas.getSelectedItem()));
                st.setString(5, NH1Guru.getText());
                st.setString(6, NH2Guru.getText());
                st.setString(7, NH3Guru.getText());
                st.setString(8, NUTSGuru.getText());
                st.setString(9, NUASGuru.getText());
                st.setString(10, txtNIS.getText());
                st.setString(11, txtNamaSiswa.getText());
                st.setString(12, NH1.getText());
                st.setString(13, NH2.getText());
                st.setString(14, NH3.getText());
                st.setString(15, NUTS.getText());
                st.setString(16, NUAS.getText());
                st.setString(17, NAKHIR.getText());
                st.setString(18, Tahun.getText());
            int rs=st.executeUpdate();

            if(rs>0){
            JOptionPane.showMessageDialog(this,"Input Berhasil");
      	    tampilDataKeJTable();
            }
            st.close();
            conn.close();
        }
        catch (ClassNotFoundException cnfe) {
           System.out.println("Class Driver tidak ditemukan.. : " + cnfe);
        }
        catch (SQLException sqle) {
           System.out.println("Input  Gagal = " + sqle.getMessage());
        }
        catch(Exception e){
           System.out.println("Koneksi Gagal " +e.getMessage());
        }
  }

public void hapus_Data() {
    ambilData_dari_JTable();
    int ok = JOptionPane.showConfirmDialog(this,
        "Anda Yakin Ingin Menghapus Data\nDengan nip = '" + txtNIS.getText() +
        "'", "Konfirmasi Menghapus Data",JOptionPane.YES_NO_OPTION);
    if (ok == 0) {
      try {
       Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
       conn=DriverManager.getConnection("jdbc:odbc:akademik_smppgri2bdg");
        String sql = "DELETE FROM nilai WHERE kode_mata_pelajaran = ? and nama_kelas = ? and nis = ?";
        PreparedStatement st = conn.prepareStatement(sql);
        st.setString(1, txtKodeMatpel.getText());
        st.setString(2, String.valueOf(CBKelas.getSelectedItem()));
        st.setString(3, txtNIS.getText());
        int rs=st.executeUpdate();
        if(rs>0){
        tampilDataKeJTable();
        JOptionPane.showMessageDialog(this,"Data Sudah dihapus");
        }
        CBKelas.setSelectedItem("--Pilih--");
        txtNIS.setText("");
        txtNamaSiswa.setText("");
        NH1.setText("");
        NH2.setText("");
        NH3.setText("");
        NUTS.setText("");
        NUAS.setText("");
        NAKHIR.setText("");

      } catch (Exception se) {
         JOptionPane.showMessageDialog(this,"Gagal Hapus Data.. ");
       }
    }
  }

    private void persentase(String text, String text0, String text1, String text2, String text3) {
        int persen1=Integer.valueOf(text);
        int persen2=Integer.valueOf(text0);
        int persen3=Integer.valueOf(text1);
        int persen4=Integer.valueOf(text2);
        int persen5=Integer.valueOf(text3);
        if ((persen1+persen2+persen3+persen4+persen5) > 100)
        {
            JOptionPane.showMessageDialog(this,"Persentase Nilai yang Anda Masukan Tidak Valid");
        }
    }

    private void persentase2(String text, String text0, String text1, String text2, String text3) {
        int persen1=Integer.valueOf(text);
        int persen2=Integer.valueOf(text0);
        int persen3=Integer.valueOf(text1);
        int persen4=Integer.valueOf(text2);
        int persen5=Integer.valueOf(text3);
        if ((persen1+persen2+persen3+persen4+persen5) != 100)
        {
            JOptionPane.showMessageDialog(this,"Persentase Nilai yang Anda Masukan Tidak Valid");
        }
        else
        {
         int nh1guru,nh2guru,nh3guru,nutsguru,nuasguru,nh1,nh2,nh3,nuts,nuas,nakhir;
        nh1guru=Integer.parseInt(NH1Guru.getText());
        nh2guru=Integer.parseInt(NH2Guru.getText());
        nh3guru=Integer.parseInt(NH3Guru.getText());
        nutsguru=Integer.parseInt(NUTSGuru.getText());
        nuasguru=Integer.parseInt(NUASGuru.getText());

        nh1=Integer.parseInt(NH1.getText());
        nh2=Integer.parseInt(NH2.getText());
        nh3=Integer.parseInt(NH3.getText());
        nuts=Integer.parseInt(NUTS.getText());
        nuas=Integer.parseInt(NUAS.getText());
        nakhir=(nh1*nh1guru/100)+(nh2*nh2guru/100)+(nh3*nh3guru/100)+(nuts*nutsguru/100)+(nuas*nuasguru/100);
        NAKHIR.setText(String.valueOf(nakhir));
        }
    }

    private void persentetap() {
        try {
        conn.close();
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        conn=DriverManager.getConnection("jdbc:odbc:akademik_smppgri2bdg");
        String sql="Select * from nilai where kode_mata_pelajaran = ?";
        PreparedStatement st=conn.prepareStatement(sql);
        st.setString(1, txtKodeMatpel.getText());
        ResultSet rs=st.executeQuery();
        boolean cek=true;
        while(rs.next()){
        cek = false;
        NH1Guru.setText(rs.getString("persentase_nh1"));
        NH2Guru.setText(rs.getString("persentase_nh2"));
        NH3Guru.setText(rs.getString("persentase_nh3"));
        NUTSGuru.setText(rs.getString("persentase_nuts"));
        NUASGuru.setText(rs.getString("persentase_nuas"));


        NH1Guru.setEnabled(false);
        NH2Guru.setEnabled(false);
        NH3Guru.setEnabled(false);
        NUTSGuru.setEnabled(false);
        NUASGuru.setEnabled(false);

        }
        if(cek)
        {
        txtKodeMatpel.setEnabled(false);
        txtNamaMatpel.setEnabled(false);
        txtNamaGuru.setEnabled(false);
        CBKelas.setEnabled(true);
        NH1Guru.setEnabled(true);
        NH2Guru.setEnabled(true);
        NH3Guru.setEnabled(true);
        NUTSGuru.setEnabled(true);
        NUASGuru.setEnabled(true);
        txtNIS.setEnabled(true);
        txtNamaSiswa.setEnabled(false);
        NH1.setEnabled(true);
        NH2.setEnabled(true);
        NH3.setEnabled(true);
        NUTS.setEnabled(true);
        NUAS.setEnabled(true);
        NAKHIR.setEnabled(true);
        BHitung.setEnabled(true);
        Tahun.setEnabled(false);
        }
  }
    catch (Exception e) {}
    }

    private void setJTable2() {
     String [] JudulKolom={"No","NIS","Nama Siswa"};
    tabModel2 = new DefaultTableModel(null, JudulKolom){
                  boolean[] canEdit = new boolean [] { false, false, false };
                  @Override
                  public boolean isCellEditable(int rowIndex, int columnIndex) {
                   return canEdit [columnIndex];
                  }
              };
    TSiswa.setModel(tabModel2);
    TSiswa.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
    TSiswa.getColumnModel().getColumn(0).setPreferredWidth(30);
    TSiswa.getColumnModel().getColumn(1).setPreferredWidth(100);
    TSiswa.getColumnModel().getColumn(2).setPreferredWidth(170);


    getData2();
    }

    private void getData2() {
          try{
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");

        conn=DriverManager.getConnection("jdbc:odbc:akademik_smppgri2bdg");

        String sql="Select * from siswa order by nis";
        PreparedStatement st=conn.prepareStatement(sql);

        ResultSet rs=st.executeQuery();

        String nis,nama_siswa;
        int no=0;
        while(rs.next()){
         no=no+1;
         nis=rs.getString("nis");
         nama_siswa=rs.getString("nama_siswa");
         Object [] Data = {no,nis,nama_siswa};
         tabModel2.addRow(Data);
        }

          st.close();
          conn.close();
    }
    catch (ClassNotFoundException cnfe) {
           System.out.println("Class Driver tidak ditemukan.. : " + cnfe);
           System.exit(0);
    }
    catch (SQLException sqle) {
           System.out.println("Proses Query Gagal = " + sqle);
           System.exit(0);
    }
    catch(Exception e){
           System.out.println("Koneksi Access Gagal " +e.getMessage());
           System.exit(0);
    }

    }
}

